(() => {
 const C=window.P132_CONFIG;if(!C){document.body.innerHTML='<main><h2>尚未建立 config.js</h2><p>請由 config-sample.js 複製建立 config.js。</p></main>';return;}
 const sb=supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY,{auth:{storageKey:'P132-auth',persistSession:true}});
 const $=id=>document.getElementById(id); let current=null,showOriginal=false,activePopover=null,feedItems=[],currentFeedIndex=-1;
 ['registerLink','forgotLink'].forEach(id=>$(id).href=C.P130_URL||'#');
 async function boot(){const {data:{session}}=await sb.auth.getSession();show(session);if(session)await init();}
 function show(s){$('auth').hidden=!!s;$('app').hidden=!s;}
 $('login').onclick=async()=>{const {error}=await sb.auth.signInWithPassword({email:$('email').value,password:$('password').value});$('authMsg').textContent=error?error.message:'';if(!error){show(true);await init();}};
 $('logout').onclick=async()=>{await sb.auth.signOut();location.reload();};
 $('lang').onchange=async()=>{await sb.rpc('P132_SetTargetLanguage',{p_language:$('lang').value});await loadFeed();};
 async function init(){const {data:p,error}=await sb.rpc('P132_EnsureLearnerProfile');if(error)return alert(error.message);if(p?.target_language)$('lang').value=p.target_language;await loadFeed();}
 async function loadFeed(){ $('reader').hidden=true; const {data,error}=await sb.rpc('P132_GetReadingFeed',{p_limit:20}); if(error){$('feed').textContent=error.message;return;} $('feed').innerHTML=''; feedItems=data||[]; feedItems.forEach((a,i)=>{const d=document.createElement('div');d.className='feed-item';d.innerHTML=`<h3>${esc(a.title)}</h3><p>${esc(a.summary||'')}</p><button>開始閱讀</button>`;d.querySelector('button').onclick=()=>openArticle(a.article_id,i);$('feed').appendChild(d);});}
 async function openArticle(id,index=null){if(index!==null)currentFeedIndex=index;const {data:sid,error:sessionError}=await sb.rpc('P132_StartReadingSession',{p_article_id:id});if(sessionError)return alert(sessionError.message);const {data,error}=await sb.rpc('P132_PrepareArticle',{p_article_id:id,p_reading_session_id:sid});if(error)return alert(error.message);current=data;showOriginal=false;$('toggleOriginal').textContent='顯示原文';$('prevArticle').disabled=currentFeedIndex<=0;$('nextArticle').disabled=currentFeedIndex<0||currentFeedIndex>=feedItems.length-1;$('title').textContent=data.title;$('sourceLink').href=data.original_url;$('feed').parentElement.hidden=true;$('reader').hidden=false;renderSegments(data.segments||[]);}
 function closePopover(){if(activePopover){activePopover.remove();activePopover=null;}}
 function openPopover(anchor,s){closePopover();const pop=document.createElement('div');pop.className='translation-popover';pop.innerHTML='<div class="popover-head">中文意思</div><div class="popover-meaning">讀取中…</div>';document.body.appendChild(pop);const r=anchor.getBoundingClientRect();const pr=pop.getBoundingClientRect();let left=Math.min(window.innerWidth-pr.width-8,Math.max(8,r.left));let top=r.bottom+6;if(top+pr.height>window.innerHeight-8)top=Math.max(8,r.top-pr.height-6);pop.style.left=left+'px';pop.style.top=top+'px';activePopover=pop;sb.rpc('P132_RequestTranslation',{p_exposure_id:s.exposure_id}).then(({data,error})=>{if(!pop.isConnected)return;pop.querySelector('.popover-meaning').textContent=error?error.message:(data?.meaning_zh||'—');});}
 function renderSegments(segs){closePopover();const box=$('article');box.innerHTML='';segs.forEach(s=>{if(!s.exposure_id){box.append(document.createTextNode(s.text));return;}if(showOriginal){box.append(document.createTextNode(s.text));return;}const wrap=document.createElement('span');wrap.className='vocab-wrap';const w=document.createElement('span');w.className='word';w.textContent=s.display_text;const actions=document.createElement('span');actions.className='micro-actions';const tr=document.createElement('button');tr.className='micro-icon translate';tr.type='button';tr.title='翻譯';tr.setAttribute('aria-label','翻譯');tr.textContent='●';tr.onclick=e=>{e.stopPropagation();openPopover(tr,s);};const ok=document.createElement('button');ok.className='micro-icon understand';ok.type='button';ok.title='我懂';ok.setAttribute('aria-label','我懂');ok.textContent='●';ok.onclick=async e=>{e.stopPropagation();const {error}=await sb.rpc('P132_ReportUnderstand',{p_exposure_id:s.exposure_id});if(error)return alert(error.message);ok.remove();};actions.append(tr);if(s.show_understand!==false)actions.append(ok);wrap.append(w,actions);box.append(wrap);});}
 $('toggleOriginal').onclick=()=>{if(!current)return;showOriginal=!showOriginal;$('toggleOriginal').textContent=showOriginal?'顯示漸浸版':'顯示原文';renderSegments(current.segments||[]);};
 $('prevArticle').onclick=()=>{if(currentFeedIndex>0)openArticle(feedItems[currentFeedIndex-1].article_id,currentFeedIndex-1);};
 $('nextArticle').onclick=()=>{if(currentFeedIndex>=0&&currentFeedIndex<feedItems.length-1)openArticle(feedItems[currentFeedIndex+1].article_id,currentFeedIndex+1);};
 document.addEventListener('pointerdown',e=>{if(activePopover&&!activePopover.contains(e.target)&&!e.target.closest('.translate'))closePopover();});
 document.addEventListener('keydown',e=>{if(e.key==='Escape')closePopover();});
 window.addEventListener('scroll',closePopover,{passive:true});window.addEventListener('resize',closePopover);
 function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));} boot();
})();