-- P132 V0.2 Lexicon Foundation
-- Adds provenance and Progressive-Immersion suitability metadata without changing V0.1.1 reading behavior.

create table if not exists public."TblP132LexiconSource" (
  "LexiconSourceID" bigint generated by default as identity primary key,
  "SourceCode" text not null unique,
  "SourceName" text not null,
  "SourceURL" text,
  "Description" text,
  "IsActive" boolean not null default true,
  "CreatedAt" timestamptz not null default now()
);

create table if not exists public."TblP132VocabularySourceEntry" (
  "VocabularySourceEntryID" bigint generated by default as identity primary key,
  "LexiconSourceID" bigint not null references public."TblP132LexiconSource"("LexiconSourceID"),
  "ConceptID" bigint references public."TblP132VocabularyConcept"("ConceptID") on delete set null,
  "LanguageCode" text not null check ("LanguageCode" in ('en','ja','zh-TW')),
  "SourceSurfaceForm" text not null,
  "SourceLemma" text,
  "SourceTier" text,
  "SourceOrder" integer,
  "IsBasic1200" boolean not null default false,
  "IsCommon2000" boolean not null default false,
  "ImportStatus" text not null default 'unmapped'
    check ("ImportStatus" in ('unmapped','mapped','needs_review','rejected')),
  "ImportedAt" timestamptz not null default now(),
  "ReviewedAt" timestamptz,
  "ReviewNote" text,
  unique ("LexiconSourceID","LanguageCode","SourceSurfaceForm")
);

create table if not exists public."TblP132ConceptInfiltrationPolicy" (
  "ConceptID" bigint not null references public."TblP132VocabularyConcept"("ConceptID") on delete cascade,
  "TargetLanguage" text not null check ("TargetLanguage" in ('en','ja')),
  "SuitabilityGrade" text not null default 'C'
    check ("SuitabilityGrade" in ('A','B','C','D')),
  "Phase1Eligible" boolean not null default false,
  "SuitabilityReason" text,
  "ReviewedBy" uuid,
  "ReviewedAt" timestamptz,
  "UpdatedAt" timestamptz not null default now(),
  primary key ("ConceptID","TargetLanguage")
);

create index if not exists "IdxP132VocabularySourceEntryForm"
  on public."TblP132VocabularySourceEntry"("LanguageCode","SourceSurfaceForm");
create index if not exists "IdxP132VocabularySourceEntryTier"
  on public."TblP132VocabularySourceEntry"("IsBasic1200","IsCommon2000");
create index if not exists "IdxP132ConceptInfiltrationEligible"
  on public."TblP132ConceptInfiltrationPolicy"("TargetLanguage","Phase1Eligible","SuitabilityGrade");

insert into public."TblP132LexiconSource"
  ("SourceCode","SourceName","SourceURL","Description")
values
  ('NAER_12YBE_EN_2000',
   '十二年國民基本教育英語文課程綱要參考字彙表（2,000字）',
   'https://stv.naer.edu.tw/data/course_outline/pta_18518_3555074_59836.pdf',
   '國家教育研究院英語文課程綱要附錄五；包含基本1,200字與其他常用800字。')
on conflict ("SourceCode") do update
set "SourceName"=excluded."SourceName",
    "SourceURL"=excluded."SourceURL",
    "Description"=excluded."Description",
    "IsActive"=true;

-- Important:
-- 1. Source entries are evidence/provenance records, not automatically approved P132 Concepts.
-- 2. Official Basic1200/Common2000 status must never be inferred from P132 suitability.
-- 3. Phase1Eligible is a P132 design decision and is independent of official curriculum tier.
-- 4. Importing the actual 2,000 source entries is a separate, auditable migration.
