-- P132 V0.2 Lexicon Mapping / Review Pipeline
-- Run after 06 and 07. Additive migration only.

create table if not exists public."TblP132VocabularySourceMapping" (
  "SourceMappingID" bigint generated by default as identity primary key,
  "VocabularySourceEntryID" bigint not null references public."TblP132VocabularySourceEntry"("VocabularySourceEntryID") on delete cascade,
  "ConceptID" bigint not null references public."TblP132VocabularyConcept"("ConceptID") on delete cascade,
  "MappingType" text not null default 'exact'
    check ("MappingType" in ('exact','sense','variant','related')),
  "MappingConfidence" numeric(5,4) check ("MappingConfidence" is null or "MappingConfidence" between 0 and 1),
  "ReviewStatus" text not null default 'pending'
    check ("ReviewStatus" in ('pending','approved','rejected')),
  "IsPrimary" boolean not null default false,
  "ReviewNote" text,
  "CreatedAt" timestamptz not null default now(),
  "ReviewedAt" timestamptz,
  unique ("VocabularySourceEntryID","ConceptID")
);

create index if not exists "IdxP132SourceMappingEntry"
  on public."TblP132VocabularySourceMapping"("VocabularySourceEntryID","ReviewStatus");
create index if not exists "IdxP132SourceMappingConcept"
  on public."TblP132VocabularySourceMapping"("ConceptID","ReviewStatus");

-- One source entry may map to several semantic concepts (polysemy).
-- Example: bank -> 銀行 / 河岸. Never force a 1:1 source-entry-to-concept model.

-- Link already-existing P132 English forms to official source entries only when
-- the normalized surface form matches exactly. These are candidates first.
with src as (
  select e."VocabularySourceEntryID", lower(btrim(e."SourceSurfaceForm")) as k
  from public."TblP132VocabularySourceEntry" e
  join public."TblP132LexiconSource" s on s."LexiconSourceID"=e."LexiconSourceID"
  where s."SourceCode"='NAER_12YBE_EN_2000' and e."LanguageCode"='en'
),
frm as (
  select f."ConceptID", lower(btrim(coalesce(f."Lemma",f."SurfaceForm"))) as k
  from public."TblP132VocabularyForm" f
  where f."LanguageCode"='en' and f."IsActive"=true
)
insert into public."TblP132VocabularySourceMapping"
 ("VocabularySourceEntryID","ConceptID","MappingType","MappingConfidence","ReviewStatus","IsPrimary","ReviewNote","ReviewedAt")
select s."VocabularySourceEntryID", f."ConceptID", 'exact', 1.0000, 'approved', true,
       'Exact match to an existing P132 English form at V0.2 migration time.', now()
from src s join frm f using(k)
on conflict ("VocabularySourceEntryID","ConceptID") do nothing;

-- Mark a source entry mapped only if it has at least one approved mapping.
update public."TblP132VocabularySourceEntry" e
set "ImportStatus"='mapped',
    "ReviewedAt"=coalesce(e."ReviewedAt",now())
where exists (
  select 1 from public."TblP132VocabularySourceMapping" m
  where m."VocabularySourceEntryID"=e."VocabularySourceEntryID"
    and m."ReviewStatus"='approved'
);

-- Initialize infiltration-policy rows for mapped existing concepts.
-- Conservative default: C / not eligible. Suitability is a separate P132 review.
insert into public."TblP132ConceptInfiltrationPolicy"
 ("ConceptID","TargetLanguage","SuitabilityGrade","Phase1Eligible","SuitabilityReason")
select distinct m."ConceptID",'en','C',false,
       'Awaiting explicit P132 infiltration-suitability review.'
from public."TblP132VocabularySourceMapping" m
where m."ReviewStatus"='approved'
on conflict ("ConceptID","TargetLanguage") do nothing;

-- Review queue view. Source truth remains in the tables above.
create or replace view public."VwP132LexiconReviewQueue" as
select
 e."VocabularySourceEntryID",
 e."SourceSurfaceForm",
 e."SourceTier",
 e."IsBasic1200",
 e."ImportStatus",
 m."SourceMappingID",
 m."ConceptID",
 c."CanonicalZh",
 c."MeaningZh",
 m."MappingType",
 m."MappingConfidence",
 m."ReviewStatus" as "MappingReviewStatus",
 p."SuitabilityGrade",
 p."Phase1Eligible",
 p."SuitabilityReason"
from public."TblP132VocabularySourceEntry" e
join public."TblP132LexiconSource" s on s."LexiconSourceID"=e."LexiconSourceID"
left join public."TblP132VocabularySourceMapping" m
  on m."VocabularySourceEntryID"=e."VocabularySourceEntryID"
left join public."TblP132VocabularyConcept" c on c."ConceptID"=m."ConceptID"
left join public."TblP132ConceptInfiltrationPolicy" p
  on p."ConceptID"=m."ConceptID" and p."TargetLanguage"='en'
where s."SourceCode"='NAER_12YBE_EN_2000';

-- Audit
select
 count(*) filter(where "ImportStatus"='mapped') as "MappedSourceEntries",
 count(*) filter(where "ImportStatus"='unmapped') as "UnmappedSourceEntries",
 count(*) as "TotalSourceEntries"
from public."TblP132VocabularySourceEntry" e
join public."TblP132LexiconSource" s using("LexiconSourceID")
where s."SourceCode"='NAER_12YBE_EN_2000';
