-- P132 SQL15
-- Chinese Reading Scaffold Architecture
-- Purpose: preserve foreign-language RSS originals while storing versioned Chinese
-- reading scaffolds as derived material. This migration does NOT call any AI service.

create table if not exists public."TblP132ArticleScaffold"(
  "ScaffoldID" bigint generated by default as identity primary key,
  "ArticleID" bigint not null references public."TblP132Article"("ArticleID") on delete cascade,
  "ScaffoldLanguage" text not null default 'zh-TW',
  "TitleText" text,
  "SummaryText" text,
  "ContentText" text,
  "GenerationMethod" text not null default 'ai_translation',
  "ProviderName" text,
  "ModelName" text,
  "GenerationVersion" text not null,
  "SourceContentHash" text,
  "Status" text not null default 'draft',
  "IsCurrent" boolean not null default false,
  "GeneratedAt" timestamptz,
  "ReviewedAt" timestamptz,
  "CreatedAt" timestamptz not null default now(),
  "UpdatedAt" timestamptz not null default now(),
  constraint "ChkP132ScaffoldLanguage" check("ScaffoldLanguage"='zh-TW'),
  constraint "ChkP132ScaffoldMethod" check("GenerationMethod" in('ai_translation','human_translation','hybrid')),
  constraint "ChkP132ScaffoldStatus" check("Status" in('draft','ready','reviewed','rejected')),
  constraint "ChkP132ScaffoldCurrentReady" check(not "IsCurrent" or "Status" in('ready','reviewed')),
  constraint "ChkP132ScaffoldHasText" check(
    nullif(btrim(coalesce("TitleText",'')),'') is not null
    or nullif(btrim(coalesce("SummaryText",'')),'') is not null
    or nullif(btrim(coalesce("ContentText",'')),'') is not null
  )
);

create index if not exists "IdxP132ScaffoldArticle"
  on public."TblP132ArticleScaffold"("ArticleID","ScaffoldLanguage","CreatedAt" desc);

-- Exactly one current scaffold per article/language; old versions remain for provenance.
create unique index if not exists "UqP132ScaffoldCurrent"
  on public."TblP132ArticleScaffold"("ArticleID","ScaffoldLanguage")
  where "IsCurrent";

alter table public."TblP132ArticleScaffold" enable row level security;

-- Scaffold rows are derived/back-office data. Learners do not write them directly.
revoke all on table public."TblP132ArticleScaffold" from public,anon,authenticated;
grant select,insert,update,delete on table public."TblP132ArticleScaffold" to service_role;
grant usage,select on sequence public."TblP132ArticleScaffold_ScaffoldID_seq" to service_role;

-- Back-office helper: insert a new scaffold version and optionally make it current.
-- It intentionally does not expose authenticated browser execution.
create or replace function public."P132_SaveArticleScaffold"(
  p_article_id bigint,
  p_title_text text,
  p_summary_text text,
  p_content_text text,
  p_generation_method text,
  p_provider_name text,
  p_model_name text,
  p_generation_version text,
  p_source_content_hash text default null,
  p_status text default 'ready',
  p_make_current boolean default true
)
returns bigint
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  sid bigint;
  source_lang text;
begin
  select "LanguageCode" into source_lang
  from public."TblP132Article"
  where "ArticleID"=p_article_id;
  if not found then raise exception 'Article not found'; end if;
  if source_lang='zh-TW' then
    raise exception 'Chinese-source articles do not require a Chinese scaffold';
  end if;
  if nullif(btrim(coalesce(p_generation_version,'')),'') is null then
    raise exception 'GenerationVersion is required';
  end if;
  if p_make_current and p_status not in('ready','reviewed') then
    raise exception 'Only ready/reviewed scaffolds can be current';
  end if;

  if p_make_current then
    update public."TblP132ArticleScaffold"
    set "IsCurrent"=false,"UpdatedAt"=now()
    where "ArticleID"=p_article_id and "ScaffoldLanguage"='zh-TW' and "IsCurrent";
  end if;

  insert into public."TblP132ArticleScaffold"(
    "ArticleID","ScaffoldLanguage","TitleText","SummaryText","ContentText",
    "GenerationMethod","ProviderName","ModelName","GenerationVersion",
    "SourceContentHash","Status","IsCurrent","GeneratedAt"
  ) values(
    p_article_id,'zh-TW',p_title_text,p_summary_text,p_content_text,
    p_generation_method,p_provider_name,p_model_name,p_generation_version,
    p_source_content_hash,p_status,p_make_current,now()
  ) returning "ScaffoldID" into sid;

  return sid;
end $$;

revoke all on function public."P132_SaveArticleScaffold"(bigint,text,text,text,text,text,text,text,text,text,boolean) from public,anon,authenticated;
grant execute on function public."P132_SaveArticleScaffold"(bigint,text,text,text,text,text,text,text,text,text,boolean) to service_role;

-- Learner-facing read RPC. Returns only the current ready/reviewed scaffold.
create or replace function public."P132_GetArticleScaffold"(p_article_id bigint)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  uid uuid:=auth.uid();
  r record;
begin
  if uid is null then raise exception 'Authentication required'; end if;

  select s."ScaffoldID",s."ArticleID",s."ScaffoldLanguage",s."TitleText",
         s."SummaryText",s."ContentText",s."GenerationMethod",s."ProviderName",
         s."ModelName",s."GenerationVersion",s."GeneratedAt",a."LanguageCode" as "SourceLanguage"
  into r
  from public."TblP132ArticleScaffold" s
  join public."TblP132Article" a on a."ArticleID"=s."ArticleID"
  where s."ArticleID"=p_article_id and s."ScaffoldLanguage"='zh-TW'
    and s."IsCurrent" and s."Status" in('ready','reviewed')
    and a."IsPublished"
  order by s."CreatedAt" desc
  limit 1;

  if not found then return null; end if;
  return jsonb_build_object(
    'scaffold_id',r."ScaffoldID",'article_id',r."ArticleID",
    'source_language',r."SourceLanguage",'scaffold_language',r."ScaffoldLanguage",
    'title',r."TitleText",'summary',r."SummaryText",'content_text',r."ContentText",
    'generation_method',r."GenerationMethod",'provider_name',r."ProviderName",
    'model_name',r."ModelName",'generation_version',r."GenerationVersion",
    'generated_at',r."GeneratedAt"
  );
end $$;

revoke all on function public."P132_GetArticleScaffold"(bigint) from public,anon;
grant execute on function public."P132_GetArticleScaffold"(bigint) to authenticated;

-- Audit
select column_name,data_type,is_nullable
from information_schema.columns
where table_schema='public' and table_name='TblP132ArticleScaffold'
order by ordinal_position;
