-- P132 SQL16
-- 16_P132_LinguisticAnnotation_ProtectedSpan.sql
-- Protected-span layer for Chinese lexical annotation.
--
-- Goal:
--   Prevent false partial replacement inside protected expressions, especially proper nouns.
--   Example: 湖口 must not become lake口 merely because 湖 is an eligible Concept.
--
-- Pipeline:
--   Source Text -> Linguistic Annotation / Protected Span -> Concept matching -> Form -> Evidence -> State
--
-- Principles:
-- * A protected span blocks partial lexical matches inside that span.
-- * If the entire protected span itself is an approved Concept, exact whole-span matching remains allowed.
-- * Protection is article-specific and versioned.
-- * Manual protection has priority and is never deleted by automatic refresh.
-- * This migration does NOT pretend to solve full Chinese NER/WSD.
-- * Conservative rule: missing one exposure is preferable to a wrong replacement.

create table if not exists public."TblP132ArticleProtectedSpan"(
  "ProtectedSpanID" bigint generated by default as identity primary key,
  "ArticleID" bigint not null references public."TblP132Article"("ArticleID") on delete cascade,
  "OriginalText" text not null,
  "StartOffset" integer not null,
  "EndOffset" integer not null,
  "SpanType" text not null default 'proper_noun',
  "DetectionMethod" text not null default 'manual',
  "AnnotationVersion" text not null default 'P132-ANNOT-0.1',
  "Confidence" numeric(5,4),
  "Note" text,
  "CreatedAt" timestamptz not null default now(),
  constraint "ChkP132ProtectedSpanOffsets" check ("StartOffset">=0 and "EndOffset">"StartOffset"),
  constraint "ChkP132ProtectedSpanType" check ("SpanType" in
    ('proper_noun','place_name','person_name','organization','brand','title','fixed_expression','other')),
  constraint "ChkP132ProtectedSpanMethod" check ("DetectionMethod" in
    ('manual','gazetteer','rule','nlp','ai')),
  constraint "ChkP132ProtectedSpanConfidence" check ("Confidence" is null or ("Confidence">=0 and "Confidence"<=1)),
  unique("ArticleID","StartOffset","EndOffset")
);

create index if not exists "IdxP132ProtectedSpanArticle"
  on public."TblP132ArticleProtectedSpan"("ArticleID","StartOffset","EndOffset");

alter table public."TblP132ArticleProtectedSpan" enable row level security;

revoke all on table public."TblP132ArticleProtectedSpan" from public;
revoke all on table public."TblP132ArticleProtectedSpan" from anon;
revoke all on table public."TblP132ArticleProtectedSpan" from authenticated;
grant select,insert,update,delete on table public."TblP132ArticleProtectedSpan" to service_role;
grant usage,select on sequence public."TblP132ArticleProtectedSpan_ProtectedSpanID_seq" to service_role;

-- Back-office helper: protect every exact occurrence of a known expression in one article.
-- Useful immediately for place names such as 湖口 / 湖口鄉 without introducing a full NLP stack.
create or replace function public."P132_AddProtectedExpression"(
  p_article_id bigint,
  p_expression text,
  p_span_type text default 'proper_noun',
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  body text;
  pos integer;
  n integer:=0;
begin
  if nullif(btrim(p_expression),'') is null then
    raise exception 'Expression is required';
  end if;
  if p_span_type not in ('proper_noun','place_name','person_name','organization','brand','title','fixed_expression','other') then
    raise exception 'Invalid span type';
  end if;

  select coalesce("ContentText","Summary",'') into body
  from public."TblP132Article"
  where "ArticleID"=p_article_id and "IsPublished";

  if not found then raise exception 'Article not found'; end if;

  for pos in
    select g
    from generate_series(1,greatest(1,length(body)-char_length(p_expression)+1)) g
    where substring(body from g for char_length(p_expression))=p_expression
  loop
    insert into public."TblP132ArticleProtectedSpan"
      ("ArticleID","OriginalText","StartOffset","EndOffset","SpanType",
       "DetectionMethod","AnnotationVersion","Confidence","Note")
    values
      (p_article_id,p_expression,pos-1,(pos-1)+char_length(p_expression),p_span_type,
       'manual','P132-ANNOT-0.1',1.0000,p_note)
    on conflict("ArticleID","StartOffset","EndOffset") do update set
      "OriginalText"=excluded."OriginalText",
      "SpanType"=excluded."SpanType",
      "DetectionMethod"='manual',
      "AnnotationVersion"=excluded."AnnotationVersion",
      "Confidence"=1.0000,
      "Note"=coalesce(excluded."Note",public."TblP132ArticleProtectedSpan"."Note");
    n:=n+1;
  end loop;

  return jsonb_build_object(
    'article_id',p_article_id,
    'expression',p_expression,
    'protected_occurrences',n,
    'annotation_version','P132-ANNOT-0.1'
  );
end $$;

revoke all on function public."P132_AddProtectedExpression"(bigint,text,text,text) from public;
revoke all on function public."P132_AddProtectedExpression"(bigint,text,text,text) from anon;
revoke all on function public."P132_AddProtectedExpression"(bigint,text,text,text) from authenticated;
grant execute on function public."P132_AddProtectedExpression"(bigint,text,text,text) to service_role;

-- Matcher V0.3: protected-span aware.
create or replace function public."P132_AnnotateArticleOccurrences"(p_article_id bigint)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  a public."TblP132Article";
  body text;
  inserted_count integer:=0;
begin
  select * into a
  from public."TblP132Article"
  where "ArticleID"=p_article_id and "IsPublished";

  if not found then raise exception 'Article not found'; end if;
  if a."LanguageCode"<>'zh-TW' then
    return jsonb_build_object('article_id',p_article_id,'inserted',0,'reason','non_zh_tw_article');
  end if;

  body:=coalesce(a."ContentText",a."Summary",'');
  if body='' then
    return jsonb_build_object('article_id',p_article_id,'inserted',0,'reason','empty_article');
  end if;

  create temporary table if not exists pg_temp.p132_match_candidate(
    "ConceptID" bigint,
    "OriginalText" text,
    "StartOffset" integer,
    "EndOffset" integer,
    "TokenLength" integer,
    primary key("ConceptID","StartOffset","EndOffset")
  ) on commit drop;
  truncate pg_temp.p132_match_candidate;

  insert into pg_temp.p132_match_candidate
    ("ConceptID","OriginalText","StartOffset","EndOffset","TokenLength")
  select distinct c."ConceptID",c."CanonicalZh",
         pos-1,(pos-1)+char_length(c."CanonicalZh"),char_length(c."CanonicalZh")
  from public."TblP132VocabularyConcept" c
  cross join lateral generate_series(
    1,greatest(1,length(body)-char_length(c."CanonicalZh")+1)
  ) pos
  where c."IsActive" and c."ReviewStatus"='approved'
    and char_length(c."CanonicalZh")>=1
    and substring(body from pos for char_length(c."CanonicalZh"))=c."CanonicalZh"
    and exists(
      select 1 from public."TblP132ConceptInfiltrationPolicy" p
      where p."ConceptID"=c."ConceptID" and p."Phase1Eligible"
        and p."SuitabilityGrade" in('A','B')
    )
    and exists(
      select 1 from public."TblP132VocabularyForm" f
      where f."ConceptID"=c."ConceptID"
        and f."LanguageCode" in('en','ja') and f."IsActive"
    );

  -- Protected-span rule:
  -- Reject any candidate that overlaps a protected span unless it is EXACTLY the same span.
  -- Therefore 湖 inside [湖口] is blocked, while a future whole Concept 湖口 may still match.
  delete from pg_temp.p132_match_candidate c
  using public."TblP132ArticleProtectedSpan" p
  where p."ArticleID"=p_article_id
    and c."StartOffset"<p."EndOffset"
    and c."EndOffset">p."StartOffset"
    and not (
      c."StartOffset"=p."StartOffset"
      and c."EndOffset"=p."EndOffset"
    );

  -- Existing curated/manual occurrences always win.
  delete from pg_temp.p132_match_candidate c
  using public."TblP132ArticleOccurrence" o
  where o."ArticleID"=p_article_id
    and c."StartOffset"<o."EndOffset" and c."EndOffset">o."StartOffset";

  -- Deterministic longest-match selection.
  -- A candidate loses only when a directly overlapping candidate has higher priority.
  delete from pg_temp.p132_match_candidate loser
  where exists(
    select 1
    from pg_temp.p132_match_candidate winner
    where winner."ConceptID"<>loser."ConceptID"
      and winner."StartOffset"<loser."EndOffset"
      and winner."EndOffset">loser."StartOffset"
      and (
        winner."TokenLength">loser."TokenLength"
        or (winner."TokenLength"=loser."TokenLength" and winner."StartOffset"<loser."StartOffset")
        or (winner."TokenLength"=loser."TokenLength"
            and winner."StartOffset"=loser."StartOffset"
            and winner."ConceptID"<loser."ConceptID")
      )
  );

  insert into public."TblP132ArticleOccurrence"
    ("ArticleID","ConceptID","OriginalText","StartOffset","EndOffset",
     "ContextText","ReplacementEligible","MatchConfidence")
  select p_article_id,c."ConceptID",c."OriginalText",c."StartOffset",c."EndOffset",
         substring(body from greatest(1,c."StartOffset"-30)+1
                   for least(length(body),c."EndOffset"+30)-greatest(0,c."StartOffset"-30)),
         true,1.0000
  from pg_temp.p132_match_candidate c
  where not exists(
    select 1 from public."TblP132ArticleOccurrence" o
    where o."ArticleID"=p_article_id
      and c."StartOffset"<o."EndOffset" and c."EndOffset">o."StartOffset"
  )
  order by c."StartOffset"
  on conflict("ArticleID","StartOffset","EndOffset") do nothing;

  get diagnostics inserted_count=row_count;

  return jsonb_build_object(
    'article_id',p_article_id,
    'inserted',inserted_count,
    'matcher_version','P132-MATCH-0.3',
    'annotation_version','P132-ANNOT-0.1',
    'method','protected_span_exact_canonical_zh_longest_match'
  );
end $$;

create or replace function public."P132_AnnotatePublishedArticles"(p_limit integer default 50)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare r record; n int:=0; total_inserted int:=0; result jsonb;
begin
  for r in
    select "ArticleID" from public."TblP132Article"
    where "IsPublished" and "LanguageCode"='zh-TW'
    order by "ArticleID"
    limit least(greatest(p_limit,1),500)
  loop
    result:=public."P132_AnnotateArticleOccurrences"(r."ArticleID");
    n:=n+1;
    total_inserted:=total_inserted+coalesce((result->>'inserted')::int,0);
  end loop;
  return jsonb_build_object(
    'articles_processed',n,
    'occurrences_inserted',total_inserted,
    'matcher_version','P132-MATCH-0.3',
    'annotation_version','P132-ANNOT-0.1'
  );
end $$;

revoke all on function public."P132_AnnotateArticleOccurrences"(bigint) from public;
revoke all on function public."P132_AnnotateArticleOccurrences"(bigint) from anon;
revoke all on function public."P132_AnnotateArticleOccurrences"(bigint) from authenticated;
revoke all on function public."P132_AnnotatePublishedArticles"(integer) from public;
revoke all on function public."P132_AnnotatePublishedArticles"(integer) from anon;
revoke all on function public."P132_AnnotatePublishedArticles"(integer) from authenticated;
grant execute on function public."P132_AnnotateArticleOccurrences"(bigint) to service_role;
grant execute on function public."P132_AnnotatePublishedArticles"(integer) to service_role;

-- Important migration note:
-- Existing wrong automatic occurrences are intentionally NOT deleted here.
-- First add/derive protected spans, then selectively rebuild affected automatic annotations.
-- Manual occurrences must not be destroyed by a blanket cleanup.

-- Audit
select
  p."ArticleID",p."OriginalText",p."StartOffset",p."EndOffset",
  p."SpanType",p."DetectionMethod",p."AnnotationVersion"
from public."TblP132ArticleProtectedSpan" p
order by p."ArticleID",p."StartOffset";
