-- P132 SQL16B
-- 16B_P132_SharedProtectedExpression_AutoDetection.sql
-- Linguistic Annotation Pipeline V0.2
-- Gazetteer -> high-confidence suffix rules -> Article Protected Span -> Matcher V0.3
--
-- Conservative policy: precision over recall. A missed exposure is preferable
-- to a false partial replacement such as 湖口 -> lake口.

create table if not exists public."TblP132ProtectedExpression"(
  "ProtectedExpressionID" bigint generated by default as identity primary key,
  "ExpressionText" text not null,
  "SpanType" text not null default 'proper_noun',
  "LanguageCode" text not null default 'zh-TW',
  "SourceType" text not null default 'manual',
  "Confidence" numeric(5,4) not null default 1.0000,
  "Note" text,
  "IsActive" boolean not null default true,
  "CreatedAt" timestamptz not null default now(),
  "UpdatedAt" timestamptz not null default now(),
  constraint "ChkP132ProtectedExpressionText" check (char_length(btrim("ExpressionText"))>=2),
  constraint "ChkP132ProtectedExpressionSpanType" check ("SpanType" in
    ('proper_noun','place_name','person_name','organization','brand','title','fixed_expression','other')),
  constraint "ChkP132ProtectedExpressionSourceType" check ("SourceType" in
    ('manual','seed','gazetteer','reviewed')),
  constraint "ChkP132ProtectedExpressionConfidence" check ("Confidence">=0 and "Confidence"<=1),
  unique("ExpressionText","SpanType","LanguageCode")
);

create index if not exists "IdxP132ProtectedExpressionActiveText"
  on public."TblP132ProtectedExpression"("LanguageCode","IsActive","ExpressionText");

alter table public."TblP132ProtectedExpression" enable row level security;
revoke all on table public."TblP132ProtectedExpression" from public;
revoke all on table public."TblP132ProtectedExpression" from anon;
revoke all on table public."TblP132ProtectedExpression" from authenticated;
grant select,insert,update,delete on table public."TblP132ProtectedExpression" to service_role;
grant usage,select on sequence public."TblP132ProtectedExpression_ProtectedExpressionID_seq" to service_role;

-- Small reviewed seed only. This is intentionally not an attempt to become
-- a complete Taiwan entity database.
insert into public."TblP132ProtectedExpression"
  ("ExpressionText","SpanType","LanguageCode","SourceType","Confidence","Note")
values
  ('湖口','place_name','zh-TW','seed',1.0000,'Taiwan place name'),
  ('湖口鄉','place_name','zh-TW','seed',1.0000,'Taiwan township'),
  ('花蓮','place_name','zh-TW','seed',1.0000,'Taiwan place name'),
  ('花蓮縣','place_name','zh-TW','seed',1.0000,'Taiwan county'),
  ('中央社','organization','zh-TW','seed',1.0000,'Central News Agency'),
  ('慈濟大學','organization','zh-TW','seed',1.0000,'University name')
on conflict("ExpressionText","SpanType","LanguageCode") do update set
  "IsActive"=true,
  "Confidence"=excluded."Confidence",
  "UpdatedAt"=now();

-- Detect article-level protected spans.
-- Automatic rows from prior runs are refreshed; manual rows are preserved.
create or replace function public."P132_DetectProtectedSpans"(p_article_id bigint)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  a public."TblP132Article";
  body text;
  inserted_gazetteer integer:=0;
  inserted_rules integer:=0;
begin
  select * into a
  from public."TblP132Article"
  where "ArticleID"=p_article_id and "IsPublished";
  if not found then raise exception 'Article not found'; end if;

  if a."LanguageCode"<>'zh-TW' then
    return jsonb_build_object('article_id',p_article_id,'protected_spans',0,
      'reason','non_zh_tw_article','annotation_version','P132-ANNOT-0.2');
  end if;

  body:=coalesce(a."ContentText",a."Summary",'');
  if body='' then
    return jsonb_build_object('article_id',p_article_id,'protected_spans',0,
      'reason','empty_article','annotation_version','P132-ANNOT-0.2');
  end if;

  -- Recompute only machine-created rows. Human/manual annotations survive.
  delete from public."TblP132ArticleProtectedSpan"
  where "ArticleID"=p_article_id
    and "DetectionMethod" in ('gazetteer','rule','nlp','ai');

  -- 1. Shared reviewed Gazetteer: exact expression matching.
  insert into public."TblP132ArticleProtectedSpan"
    ("ArticleID","OriginalText","StartOffset","EndOffset","SpanType",
     "DetectionMethod","AnnotationVersion","Confidence","Note")
  select p_article_id,e."ExpressionText",g-1,(g-1)+char_length(e."ExpressionText"),
         e."SpanType",'gazetteer','P132-ANNOT-0.2',e."Confidence",
         'Shared Protected Expression #'||e."ProtectedExpressionID"
  from public."TblP132ProtectedExpression" e
  cross join lateral generate_series(
    1,greatest(1,length(body)-char_length(e."ExpressionText")+1)
  ) g
  where e."IsActive" and e."LanguageCode"='zh-TW'
    and substring(body from g for char_length(e."ExpressionText"))=e."ExpressionText"
  on conflict("ArticleID","StartOffset","EndOffset") do update set
    "OriginalText"=excluded."OriginalText",
    "SpanType"=excluded."SpanType",
    "DetectionMethod"=case
      when public."TblP132ArticleProtectedSpan"."DetectionMethod"='manual' then 'manual'
      else excluded."DetectionMethod" end,
    "AnnotationVersion"=case
      when public."TblP132ArticleProtectedSpan"."DetectionMethod"='manual'
        then public."TblP132ArticleProtectedSpan"."AnnotationVersion"
      else excluded."AnnotationVersion" end,
    "Confidence"=greatest(coalesce(public."TblP132ArticleProtectedSpan"."Confidence",0),
                          coalesce(excluded."Confidence",0)),
    "Note"=coalesce(public."TblP132ArticleProtectedSpan"."Note",excluded."Note");
  get diagnostics inserted_gazetteer=row_count;

  -- 2. High-confidence suffix rules.
  -- Conservative: 2-8 Han characters immediately ending in a strong entity suffix.
  -- We intentionally avoid ambiguous one-character suffixes such as 市/區/鄉 here.
  -- Those belong in the Gazetteer until a stronger boundary detector is available.
  create temporary table if not exists pg_temp.p132_rule_span(
    "OriginalText" text,"StartOffset" int,"EndOffset" int,
    "SpanType" text,"Confidence" numeric(5,4),
    primary key("StartOffset","EndOffset")
  ) on commit drop;
  truncate pg_temp.p132_rule_span;

  -- Organization suffixes with relatively strong lexical boundaries.
  insert into pg_temp.p132_rule_span
  select m[1], (rm_so-1), (rm_so-1)+char_length(m[1]), 'organization', 0.9500
  from regexp_matches(
    body,
    '([一-龥]{2,8}(大學|學院|醫院|研究院|基金會|協會|學會|委員會|股份有限公司|有限公司))',
    'g'
  ) with ordinality as z(m,ord)
  cross join lateral (
    select strpos(substr(body,coalesce((
      select max(x."EndOffset")+1 from pg_temp.p132_rule_span x
    ),1)),m[1]) + coalesce((
      select max(x."EndOffset") from pg_temp.p132_rule_span x
    ),0) as rm_so
  ) q
  where rm_so>0
  on conflict do nothing;

  -- Because SQL regexp offset handling is awkward across repeated matches,
  -- independently scan every character position for suffix-rule candidates.
  -- This second pass is authoritative and deterministic.
  truncate pg_temp.p132_rule_span;
  insert into pg_temp.p132_rule_span
  select distinct
    substring(body from s for len),
    s-1,(s-1)+len,'organization',0.9500
  from generate_series(1,length(body)) s
  cross join generate_series(4,12) len
  where s+len-1<=length(body)
    and substring(body from s for len) ~
      '^[一-龥]{2,8}(大學|學院|醫院|研究院|基金會|協會|學會|委員會|股份有限公司|有限公司)$'
    -- Keep only the longest candidate sharing the same end offset.
    and not exists(
      select 1 from generate_series(len+1,12) longer
      where s-(longer-len)>=1
        and substring(body from s-(longer-len) for longer) ~
          '^[一-龥]{2,8}(大學|學院|醫院|研究院|基金會|協會|學會|委員會|股份有限公司|有限公司)$'
    )
  on conflict do nothing;

  insert into public."TblP132ArticleProtectedSpan"
    ("ArticleID","OriginalText","StartOffset","EndOffset","SpanType",
     "DetectionMethod","AnnotationVersion","Confidence","Note")
  select p_article_id,r."OriginalText",r."StartOffset",r."EndOffset",r."SpanType",
         'rule','P132-ANNOT-0.2',r."Confidence",'High-confidence entity suffix rule'
  from pg_temp.p132_rule_span r
  where not exists(
    select 1 from public."TblP132ArticleProtectedSpan" p
    where p."ArticleID"=p_article_id
      and p."StartOffset"<=r."StartOffset" and p."EndOffset">=r."EndOffset"
  )
  on conflict("ArticleID","StartOffset","EndOffset") do nothing;
  get diagnostics inserted_rules=row_count;

  return jsonb_build_object(
    'article_id',p_article_id,
    'gazetteer_rows_affected',inserted_gazetteer,
    'rule_spans_inserted',inserted_rules,
    'protected_spans',(select count(*) from public."TblP132ArticleProtectedSpan"
                       where "ArticleID"=p_article_id),
    'annotation_version','P132-ANNOT-0.2'
  );
end $$;

-- Full annotation pipeline: protection first, lexical matching second.
create or replace function public."P132_AnnotateArticle"(p_article_id bigint)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare p jsonb; m jsonb;
begin
  p:=public."P132_DetectProtectedSpans"(p_article_id);
  m:=public."P132_AnnotateArticleOccurrences"(p_article_id);
  return jsonb_build_object(
    'article_id',p_article_id,
    'protected_span_result',p,
    'lexical_match_result',m,
    'pipeline_version','P132-LING-0.2'
  );
end $$;

create or replace function public."P132_AnnotatePublishedArticles"(p_limit integer default 50)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare r record; n int:=0; total_inserted int:=0; result jsonb;
begin
  for r in
    select "ArticleID" from public."TblP132Article"
    where "IsPublished" and "LanguageCode"='zh-TW'
    order by "ArticleID"
    limit least(greatest(p_limit,1),500)
  loop
    result:=public."P132_AnnotateArticle"(r."ArticleID");
    n:=n+1;
    total_inserted:=total_inserted+
      coalesce((result->'lexical_match_result'->>'inserted')::int,0);
  end loop;
  return jsonb_build_object(
    'articles_processed',n,
    'occurrences_inserted',total_inserted,
    'matcher_version','P132-MATCH-0.3',
    'annotation_version','P132-ANNOT-0.2',
    'pipeline_version','P132-LING-0.2'
  );
end $$;

-- Back-office only.
revoke all on function public."P132_DetectProtectedSpans"(bigint) from public;
revoke all on function public."P132_DetectProtectedSpans"(bigint) from anon;
revoke all on function public."P132_DetectProtectedSpans"(bigint) from authenticated;
revoke all on function public."P132_AnnotateArticle"(bigint) from public;
revoke all on function public."P132_AnnotateArticle"(bigint) from anon;
revoke all on function public."P132_AnnotateArticle"(bigint) from authenticated;
revoke all on function public."P132_AnnotatePublishedArticles"(integer) from public;
revoke all on function public."P132_AnnotatePublishedArticles"(integer) from anon;
revoke all on function public."P132_AnnotatePublishedArticles"(integer) from authenticated;

grant execute on function public."P132_DetectProtectedSpans"(bigint) to service_role;
grant execute on function public."P132_AnnotateArticle"(bigint) to service_role;
grant execute on function public."P132_AnnotatePublishedArticles"(integer) to service_role;

-- Verification for the known regression case.
-- After running SQL16B:
--   select public."P132_DetectProtectedSpans"(17);
-- should create/find a Gazetteer protected span for 湖口 automatically.
select "ProtectedExpressionID","ExpressionText","SpanType","SourceType","Confidence","IsActive"
from public."TblP132ProtectedExpression"
order by "ProtectedExpressionID";
