-- P132 SQL17A
-- Foreign Article Term Architecture
-- Foreign original -> multiword-first term occurrences -> Concept/Form bridge.
-- This migration stores annotation; it does not call an external NLP/AI service.

create table if not exists public."TblP132ForeignTermOccurrence"(
  "ForeignTermOccurrenceID" bigint generated by default as identity primary key,
  "ArticleID" bigint not null references public."TblP132Article"("ArticleID") on delete cascade,
  "ConceptID" bigint references public."TblP132VocabularyConcept"("ConceptID") on delete set null,
  "FormID" bigint references public."TblP132VocabularyForm"("FormID") on delete set null,
  "LanguageCode" text not null check("LanguageCode" in('en','ja')),
  "SurfaceText" text not null,
  "NormalizedTerm" text not null,
  "StartOffset" integer not null check("StartOffset">=0),
  "EndOffset" integer not null check("EndOffset">"StartOffset"),
  "TermKind" text not null default 'term' check("TermKind" in('term','multiword','proper_noun','fixed_expression')),
  "AnnotationMethod" text not null default 'lexicon' check("AnnotationMethod" in('manual','lexicon','nlp','ai')),
  "AnnotationVersion" text not null default 'P132-TERM-0.1',
  "Confidence" numeric(5,4) check("Confidence" is null or "Confidence" between 0 and 1),
  "IsActive" boolean not null default true,
  "CreatedAt" timestamptz not null default now(),
  unique("ArticleID","StartOffset","EndOffset")
);

create index if not exists "IdxP132ForeignTermArticle"
 on public."TblP132ForeignTermOccurrence"("ArticleID","StartOffset");
create index if not exists "IdxP132ForeignTermNormalized"
 on public."TblP132ForeignTermOccurrence"("LanguageCode","NormalizedTerm");

alter table public."TblP132ForeignTermOccurrence" enable row level security;
revoke all on table public."TblP132ForeignTermOccurrence" from public,anon,authenticated;
grant select,insert,update,delete on table public."TblP132ForeignTermOccurrence" to service_role;
grant usage,select on sequence public."TblP132ForeignTermOccurrence_ForeignTermOccurrenceID_seq" to service_role;

-- Conservative lexicon annotator.
-- It only recognizes active P132 forms already in the lexicon. Longer forms win,
-- so central bank is preferred over bank when both are known.
create or replace function public."P132_AnnotateForeignTerms"(p_article_id bigint)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare a public."TblP132Article"; body text; n int:=0;
begin
 select * into a from public."TblP132Article"
 where "ArticleID"=p_article_id and "IsPublished";
 if not found then raise exception 'Article not found'; end if;
 if a."LanguageCode" not in('en','ja') then
   return jsonb_build_object('article_id',p_article_id,'reason','not_foreign_source','terms_inserted',0);
 end if;
 body:=coalesce(a."ContentText",a."Summary",'');
 if body='' then return jsonb_build_object('article_id',p_article_id,'reason','empty_article','terms_inserted',0); end if;

 -- Refresh only lexicon-generated annotations; preserve manual/NLP/AI rows.
 delete from public."TblP132ForeignTermOccurrence"
 where "ArticleID"=p_article_id and "AnnotationMethod"='lexicon'
   and not exists(select 1 from public."TblP132ForeignTermExposure" x
                  where x."ForeignTermOccurrenceID"="TblP132ForeignTermOccurrence"."ForeignTermOccurrenceID");

 create temporary table if not exists pg_temp.p132_ft_candidates(
   "ConceptID" bigint,"FormID" bigint,"SurfaceText" text,"NormalizedTerm" text,
   "StartOffset" int,"EndOffset" int,"TermKind" text,"Confidence" numeric
 ) on commit drop;
 truncate pg_temp.p132_ft_candidates;

 insert into pg_temp.p132_ft_candidates
 select f."ConceptID",f."FormID",
        substring(body from g for char_length(f."SurfaceForm")),
        case when a."LanguageCode"='en' then lower(btrim(f."SurfaceForm")) else btrim(f."SurfaceForm") end,
        g-1,(g-1)+char_length(f."SurfaceForm"),
        case when f."SurfaceForm" ~ '[[:space:]]' then 'multiword' else 'term' end,1.0000
 from public."TblP132VocabularyForm" f
 join public."TblP132VocabularyConcept" c on c."ConceptID"=f."ConceptID"
 cross join lateral generate_series(1,greatest(1,length(body)-char_length(f."SurfaceForm")+1)) g
 where f."LanguageCode"=a."LanguageCode" and f."IsActive" and c."IsActive"
   and c."ReviewStatus"='approved'
   and substring(body from g for char_length(f."SurfaceForm")) =
       case when a."LanguageCode"='en' then f."SurfaceForm" else f."SurfaceForm" end
   and (a."LanguageCode"<>'en' or
        ( (g=1 or substring(body from g-1 for 1) !~ '[A-Za-z0-9]')
          and (g+char_length(f."SurfaceForm")>length(body)
               or substring(body from g+char_length(f."SurfaceForm") for 1) !~ '[A-Za-z0-9]') ));

 -- Longest-match wins. Existing non-lexicon annotations also win.
 insert into public."TblP132ForeignTermOccurrence"
 ("ArticleID","ConceptID","FormID","LanguageCode","SurfaceText","NormalizedTerm",
  "StartOffset","EndOffset","TermKind","AnnotationMethod","AnnotationVersion","Confidence")
 select p_article_id,q."ConceptID",q."FormID",a."LanguageCode",q."SurfaceText",q."NormalizedTerm",
        q."StartOffset",q."EndOffset",q."TermKind",'lexicon','P132-TERM-0.1',q."Confidence"
 from pg_temp.p132_ft_candidates q
 where not exists(
   select 1 from pg_temp.p132_ft_candidates z
   where z."StartOffset"<q."EndOffset" and z."EndOffset">q."StartOffset"
     and (z."EndOffset"-z."StartOffset")>(q."EndOffset"-q."StartOffset")
 )
 and not exists(
   select 1 from public."TblP132ForeignTermOccurrence" x
   where x."ArticleID"=p_article_id and x."IsActive"
     and x."StartOffset"<q."EndOffset" and x."EndOffset">q."StartOffset"
 )
 on conflict("ArticleID","StartOffset","EndOffset") do nothing;
 get diagnostics n=row_count;
 return jsonb_build_object('article_id',p_article_id,'language',a."LanguageCode",
   'terms_inserted',n,'annotation_version','P132-TERM-0.1','policy','multiword_first');
end $$;

revoke all on function public."P132_AnnotateForeignTerms"(bigint) from public,anon,authenticated;
grant execute on function public."P132_AnnotateForeignTerms"(bigint) to service_role;
