-- P132 SQL17B
-- Personal Meaning + Translation Candidate
-- Learner-supplied meanings are immediately usable personally, but never mutate
-- the approved Shared Lexicon without review.

create table if not exists public."TblP132PersonalTermMeaning"(
 "PersonalTermMeaningID" bigint generated by default as identity primary key,
 "UserID" uuid not null,
 "LanguageCode" text not null check("LanguageCode" in('en','ja')),
 "NormalizedTerm" text not null,
 "MeaningZh" text not null check(nullif(btrim("MeaningZh"),'') is not null),
 "ConceptID" bigint references public."TblP132VocabularyConcept"("ConceptID") on delete set null,
 "IsActive" boolean not null default true,
 "CreatedAt" timestamptz not null default now(),"UpdatedAt" timestamptz not null default now(),
 unique("UserID","LanguageCode","NormalizedTerm")
);
create table if not exists public."TblP132TranslationCandidate"(
 "TranslationCandidateID" bigint generated by default as identity primary key,
 "UserID" uuid not null,
 "ArticleID" bigint references public."TblP132Article"("ArticleID") on delete set null,
 "ForeignTermOccurrenceID" bigint references public."TblP132ForeignTermOccurrence"("ForeignTermOccurrenceID") on delete set null,
 "LanguageCode" text not null check("LanguageCode" in('en','ja')),
 "SurfaceTerm" text not null,"NormalizedTerm" text not null,"ProposedMeaningZh" text not null,
 "ContextText" text,
 "CandidateSource" text not null default 'learner' check("CandidateSource" in('learner','ai','hybrid')),
 "ReviewStatus" text not null default 'pending' check("ReviewStatus" in('pending','approved','rejected','merged')),
 "ReviewedConceptID" bigint references public."TblP132VocabularyConcept"("ConceptID") on delete set null,
 "CreatedAt" timestamptz not null default now(),"ReviewedAt" timestamptz,"ReviewNote" text
);
create index if not exists "IdxP132TranslationCandidateQueue"
 on public."TblP132TranslationCandidate"("ReviewStatus","LanguageCode","NormalizedTerm");
alter table public."TblP132PersonalTermMeaning" enable row level security;
alter table public."TblP132TranslationCandidate" enable row level security;
revoke all on table public."TblP132PersonalTermMeaning",public."TblP132TranslationCandidate" from public,anon,authenticated;
grant select,insert,update,delete on table public."TblP132PersonalTermMeaning",public."TblP132TranslationCandidate" to service_role;
grant usage,select on sequence public."TblP132PersonalTermMeaning_PersonalTermMeaningID_seq",public."TblP132TranslationCandidate_TranslationCandidateID_seq" to service_role;

create or replace function public."P132_SubmitPersonalTermMeaning"(p_occurrence_id bigint,p_meaning_zh text)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare uid uuid:=auth.uid(); o public."TblP132ForeignTermOccurrence"; aid bigint; cid bigint; ctx text;
begin
 if uid is null then raise exception 'Authentication required'; end if;
 if nullif(btrim(coalesce(p_meaning_zh,'')),'') is null then raise exception 'Meaning is required'; end if;
 select * into o from public."TblP132ForeignTermOccurrence" where "ForeignTermOccurrenceID"=p_occurrence_id and "IsActive";
 if not found then raise exception 'Term occurrence not found'; end if;
 aid:=o."ArticleID"; cid:=o."ConceptID";
 select substring(coalesce("ContentText","Summary",'')
   from greatest(1,o."StartOffset"-50)+1 for 120) into ctx
 from public."TblP132Article" where "ArticleID"=aid and "IsPublished";
 if not found then raise exception 'Article not found'; end if;

 insert into public."TblP132PersonalTermMeaning"
 ("UserID","LanguageCode","NormalizedTerm","MeaningZh","ConceptID")
 values(uid,o."LanguageCode",o."NormalizedTerm",btrim(p_meaning_zh),cid)
 on conflict("UserID","LanguageCode","NormalizedTerm") do update set
 "MeaningZh"=excluded."MeaningZh","ConceptID"=coalesce(excluded."ConceptID","TblP132PersonalTermMeaning"."ConceptID"),
 "IsActive"=true,"UpdatedAt"=now();

 insert into public."TblP132TranslationCandidate"
 ("UserID","ArticleID","ForeignTermOccurrenceID","LanguageCode","SurfaceTerm","NormalizedTerm",
  "ProposedMeaningZh","ContextText","CandidateSource")
 values(uid,aid,o."ForeignTermOccurrenceID",o."LanguageCode",o."SurfaceText",o."NormalizedTerm",
        btrim(p_meaning_zh),ctx,'learner');

 return jsonb_build_object('saved',true,'meaning_zh',btrim(p_meaning_zh),
   'scope','personal','shared_lexicon_status','pending_review');
end $$;
revoke all on function public."P132_SubmitPersonalTermMeaning"(bigint,text) from public,anon;
grant execute on function public."P132_SubmitPersonalTermMeaning"(bigint,text) to authenticated;
