-- P132 SQL17C
-- Foreign Term Exposure / Evidence / State
-- Red is always available. Green is hidden after understand and reappears after
-- a later translation_request.

create table if not exists public."TblP132ForeignTermExposure"(
 "ForeignTermExposureID" bigint generated by default as identity primary key,
 "UserID" uuid not null,
 "ReadingSessionID" uuid references public."TblP132ReadingSession"("ReadingSessionID") on delete set null,
 "ArticleID" bigint not null references public."TblP132Article"("ArticleID") on delete cascade,
 "ForeignTermOccurrenceID" bigint not null references public."TblP132ForeignTermOccurrence"("ForeignTermOccurrenceID"),
 "ConceptID" bigint references public."TblP132VocabularyConcept"("ConceptID") on delete set null,
 "LanguageCode" text not null check("LanguageCode" in('en','ja')),
 "NormalizedTerm" text not null,
 "DisplayedAt" timestamptz not null default now(),
 "AlgorithmVersion" text not null default 'P132-FOREIGN-0.1'
);
create unique index if not exists "UqP132ForeignExposureSessionOccurrence"
 on public."TblP132ForeignTermExposure"("ReadingSessionID","ForeignTermOccurrenceID")
 where "ReadingSessionID" is not null;
create table if not exists public."TblP132ForeignTermEvidence"(
 "ForeignTermEvidenceID" bigint generated by default as identity primary key,
 "ForeignTermExposureID" bigint not null references public."TblP132ForeignTermExposure"("ForeignTermExposureID") on delete cascade,
 "EvidenceType" text not null check("EvidenceType" in('translation_request','understand')),
 "OccurredAt" timestamptz not null default now(),
 unique("ForeignTermExposureID","EvidenceType")
);
create table if not exists public."TblP132LearnerForeignTermState"(
 "UserID" uuid not null,"LanguageCode" text not null check("LanguageCode" in('en','ja')),
 "NormalizedTerm" text not null,"ConceptID" bigint references public."TblP132VocabularyConcept"("ConceptID") on delete set null,
 "ExposureCount" int not null default 0,"TranslationRequestCount" int not null default 0,
 "UnderstandCount" int not null default 0,
 "LatestEvidenceType" text check("LatestEvidenceType" is null or "LatestEvidenceType" in('translation_request','understand')),
 "LastExposedAt" timestamptz,"LastTranslationAt" timestamptz,"LastUnderstandAt" timestamptz,
 "UpdatedAt" timestamptz not null default now(),
 primary key("UserID","LanguageCode","NormalizedTerm")
);
alter table public."TblP132ForeignTermExposure" enable row level security;
alter table public."TblP132ForeignTermEvidence" enable row level security;
alter table public."TblP132LearnerForeignTermState" enable row level security;
revoke all on table public."TblP132ForeignTermExposure",public."TblP132ForeignTermEvidence",public."TblP132LearnerForeignTermState" from public,anon,authenticated;
grant select,insert,update,delete on table public."TblP132ForeignTermExposure",public."TblP132ForeignTermEvidence",public."TblP132LearnerForeignTermState" to service_role;
grant usage,select on sequence public."TblP132ForeignTermExposure_ForeignTermExposureID_seq",public."TblP132ForeignTermEvidence_ForeignTermEvidenceID_seq" to service_role;

create or replace function public."P132_RecalculateForeignTermState"(p_user uuid,p_language text,p_term text)
returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare e int;t int;u int; le timestamptz;lt timestamptz;lu timestamptz; latest text; cid bigint;
begin
 if auth.uid() is null or auth.uid()<>p_user then raise exception 'Forbidden'; end if;
 select count(*),max("DisplayedAt"),max("ConceptID") into e,le,cid
 from public."TblP132ForeignTermExposure"
 where "UserID"=p_user and "LanguageCode"=p_language and "NormalizedTerm"=p_term;
 select count(*) filter(where v."EvidenceType"='translation_request'),
        count(*) filter(where v."EvidenceType"='understand'),
        max(v."OccurredAt") filter(where v."EvidenceType"='translation_request'),
        max(v."OccurredAt") filter(where v."EvidenceType"='understand')
 into t,u,lt,lu
 from public."TblP132ForeignTermEvidence" v join public."TblP132ForeignTermExposure" x
 on x."ForeignTermExposureID"=v."ForeignTermExposureID"
 where x."UserID"=p_user and x."LanguageCode"=p_language and x."NormalizedTerm"=p_term;
 select v."EvidenceType" into latest
 from public."TblP132ForeignTermEvidence" v join public."TblP132ForeignTermExposure" x
 on x."ForeignTermExposureID"=v."ForeignTermExposureID"
 where x."UserID"=p_user and x."LanguageCode"=p_language and x."NormalizedTerm"=p_term
 order by v."OccurredAt" desc,v."ForeignTermEvidenceID" desc limit 1;
 insert into public."TblP132LearnerForeignTermState"
 ("UserID","LanguageCode","NormalizedTerm","ConceptID","ExposureCount","TranslationRequestCount",
  "UnderstandCount","LatestEvidenceType","LastExposedAt","LastTranslationAt","LastUnderstandAt")
 values(p_user,p_language,p_term,cid,e,t,u,latest,le,lt,lu)
 on conflict("UserID","LanguageCode","NormalizedTerm") do update set
 "ConceptID"=coalesce(excluded."ConceptID","TblP132LearnerForeignTermState"."ConceptID"),
 "ExposureCount"=excluded."ExposureCount","TranslationRequestCount"=excluded."TranslationRequestCount",
 "UnderstandCount"=excluded."UnderstandCount","LatestEvidenceType"=excluded."LatestEvidenceType",
 "LastExposedAt"=excluded."LastExposedAt","LastTranslationAt"=excluded."LastTranslationAt",
 "LastUnderstandAt"=excluded."LastUnderstandAt","UpdatedAt"=now();
end $$;

create or replace function public."P132_GetForeignArticleTerms"(p_article_id bigint,p_reading_session_id uuid)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare uid uuid:=auth.uid(); a public."TblP132Article"; r record; eid bigint; arr jsonb:='[]'::jsonb; meaning text;
begin
 if uid is null then raise exception 'Authentication required'; end if;
 select * into a from public."TblP132Article" where "ArticleID"=p_article_id and "IsPublished" and "LanguageCode" in('en','ja');
 if not found then raise exception 'Foreign article not found'; end if;
 if not exists(select 1 from public."TblP132ReadingSession" s where s."ReadingSessionID"=p_reading_session_id
   and s."UserID"=uid and s."ArticleID"=p_article_id and s."EndedAt" is null) then raise exception 'Invalid reading session'; end if;
 for r in select o.*,s."LatestEvidenceType"
   from public."TblP132ForeignTermOccurrence" o
   left join public."TblP132LearnerForeignTermState" s on s."UserID"=uid
    and s."LanguageCode"=o."LanguageCode" and s."NormalizedTerm"=o."NormalizedTerm"
   where o."ArticleID"=p_article_id and o."IsActive" order by o."StartOffset"
 loop
   select "ForeignTermExposureID" into eid from public."TblP132ForeignTermExposure"
    where "ReadingSessionID"=p_reading_session_id and "ForeignTermOccurrenceID"=r."ForeignTermOccurrenceID";
   if eid is null then
    insert into public."TblP132ForeignTermExposure"
    ("UserID","ReadingSessionID","ArticleID","ForeignTermOccurrenceID","ConceptID","LanguageCode","NormalizedTerm")
    values(uid,p_reading_session_id,p_article_id,r."ForeignTermOccurrenceID",r."ConceptID",r."LanguageCode",r."NormalizedTerm")
    returning "ForeignTermExposureID" into eid;
   end if;
   select coalesce(pm."MeaningZh",c."MeaningZh",c."CanonicalZh") into meaning
   from (select 1) z
   left join public."TblP132PersonalTermMeaning" pm on pm."UserID"=uid and pm."LanguageCode"=r."LanguageCode"
      and pm."NormalizedTerm"=r."NormalizedTerm" and pm."IsActive"
   left join public."TblP132VocabularyConcept" c on c."ConceptID"=r."ConceptID";
   arr:=arr||jsonb_build_array(jsonb_build_object(
    'foreign_term_occurrence_id',r."ForeignTermOccurrenceID",'exposure_id',eid,
    'surface_text',r."SurfaceText",'normalized_term',r."NormalizedTerm",
    'start_offset',r."StartOffset",'end_offset',r."EndOffset",
    'term_kind',r."TermKind",'meaning_zh',meaning,
    'show_translation',true,'show_understand',coalesce(r."LatestEvidenceType",'')<>'understand'));
 end loop;
 return jsonb_build_object('article_id',p_article_id,'language',a."LanguageCode",
   'algorithm_version','P132-FOREIGN-0.1','terms',arr);
end $$;

create or replace function public."P132_ForeignTermAction"(p_exposure_id bigint,p_action text)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare uid uuid:=auth.uid(); x public."TblP132ForeignTermExposure"; meaning text;
begin
 if uid is null then raise exception 'Authentication required'; end if;
 if p_action not in('translation_request','understand') then raise exception 'Invalid action'; end if;
 select * into x from public."TblP132ForeignTermExposure"
 where "ForeignTermExposureID"=p_exposure_id and "UserID"=uid;
 if not found then raise exception 'Exposure not found'; end if;
 insert into public."TblP132ForeignTermEvidence"("ForeignTermExposureID","EvidenceType")
 values(p_exposure_id,p_action) on conflict("ForeignTermExposureID","EvidenceType")
 do update set "OccurredAt"=now();
 perform public."P132_RecalculateForeignTermState"(uid,x."LanguageCode",x."NormalizedTerm");
 if p_action='translation_request' then
   select coalesce(pm."MeaningZh",c."MeaningZh",c."CanonicalZh") into meaning
   from (select 1) z
   left join public."TblP132PersonalTermMeaning" pm on pm."UserID"=uid and pm."LanguageCode"=x."LanguageCode"
    and pm."NormalizedTerm"=x."NormalizedTerm" and pm."IsActive"
   left join public."TblP132VocabularyConcept" c on c."ConceptID"=x."ConceptID";
 end if;
 return jsonb_build_object('ok',true,'action',p_action,'meaning_zh',meaning,
   'needs_meaning_input',(p_action='translation_request' and meaning is null),
   'show_understand',(p_action='translation_request'));
end $$;

revoke all on function public."P132_RecalculateForeignTermState"(uuid,text,text) from public,anon,authenticated;
revoke all on function public."P132_GetForeignArticleTerms"(bigint,uuid) from public,anon;
revoke all on function public."P132_ForeignTermAction"(bigint,text) from public,anon;
grant execute on function public."P132_GetForeignArticleTerms"(bigint,uuid) to authenticated;
grant execute on function public."P132_ForeignTermAction"(bigint,text) to authenticated;
