-- P132 SQL17D.1
-- Multiword Term Chunking (conservative deterministic baseline)
-- Run after 17D.
--
-- Goal: promote useful learning units above raw tokens without pretending to do
-- full POS/NER parsing. Existing lexicon/manual annotations remain authoritative.
-- Unknown multiword chunks are first-class occurrences and may later grow the lexicon.
--
-- Current English rules:
--   1) known Shared-Lexicon multiword forms: highest priority (handled by 17D/17A)
--   2) selected high-confidence grammatical/lexical chunks
--   3) conservative content-word compounds (2 tokens; limited 3-token pattern)
--   4) remaining single tokens
-- Function-word-only chunks are not manufactured merely to reduce lamp count.

-- Preserve historical exposed rows. Unexposed SQL17D.1 rows may be regenerated.
-- A separate future annotation-reconciliation migration will generalize this policy.

create table if not exists public."TblP132EnglishChunkPattern"(
  "ChunkPatternID" bigint generated by default as identity primary key,
  "PatternCode" text not null unique,
  "LeftClass" text not null,
  "MiddleClass" text,
  "RightClass" text not null,
  "Priority" integer not null default 100,
  "Confidence" numeric(5,4) not null default 0.8500 check("Confidence" between 0 and 1),
  "IsActive" boolean not null default true,
  "Note" text,
  "CreatedAt" timestamptz not null default now()
);
alter table public."TblP132EnglishChunkPattern" enable row level security;
revoke all on table public."TblP132EnglishChunkPattern" from public,anon,authenticated;
grant select,insert,update,delete on table public."TblP132EnglishChunkPattern" to service_role;
grant usage,select on sequence public."TblP132EnglishChunkPattern_ChunkPatternID_seq" to service_role;

-- These are structural policies, not a phrase dictionary.
insert into public."TblP132EnglishChunkPattern"
("PatternCode","LeftClass","MiddleClass","RightClass","Priority","Confidence","Note") values
('CONTENT_CONTENT','content',null,'content',200,0.8500,
 'Two adjacent content tokens may form a learning chunk; conservative baseline.'),
('CONTENT_CONTENT_CONTENT','content','content','content',220,0.8000,
 'Three adjacent content tokens may form a chunk only when no higher-priority span exists.'),
('QUANTIFIER_THAN','quantifier',null,'than',260,0.9800,
 'High-confidence grammatical chunk such as more than / less than.'),
('TIME_AGO','time',null,'ago',260,0.9800,
 'High-confidence temporal chunk such as years ago / days ago.')
on conflict("PatternCode") do update set
 "LeftClass"=excluded."LeftClass","MiddleClass"=excluded."MiddleClass",
 "RightClass"=excluded."RightClass","Priority"=excluded."Priority",
 "Confidence"=excluded."Confidence","IsActive"=true,"Note"=excluded."Note";

create or replace function public."P132_EnglishTokenClass"(p_term text,p_kind text)
returns text language plpgsql immutable as $$
declare k text:=lower(coalesce(p_term,''));
begin
 if p_kind='function_word' then
   if k='than' then return 'than'; end if;
   return 'function';
 end if;
 if k in('more','less','fewer','greater') then return 'quantifier'; end if;
 if k in('year','years','day','days','week','weeks','month','months','hour','hours',
         'minute','minutes','second','seconds','century','centuries','decade','decades') then
   return 'time';
 end if;
 if k='ago' then return 'ago'; end if;
 return 'content';
end $$;

-- Chunk the current active token stream for one English article.
-- Important: this function does not delete exposed history.
create or replace function public."P132_ChunkEnglishArticle"(p_article_id bigint)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare
 a public."TblP132Article"; body text; r record; n int:=0; disabled int:=0;
begin
 select * into a from public."TblP132Article"
 where "ArticleID"=p_article_id and "IsPublished";
 if not found then raise exception 'Article not found'; end if;
 if a."LanguageCode"<>'en' then
   return jsonb_build_object('article_id',p_article_id,'reason','not_english','chunks_inserted',0);
 end if;
 body:=coalesce(a."ContentText",a."Summary",'');

 -- Remove only regenerable, unexposed chunk rows from this version.
 delete from public."TblP132ForeignTermOccurrence" o
 where o."ArticleID"=p_article_id and o."AnnotationMethod"='rule'
   and o."AnnotationVersion"='P132-TERM-0.3'
   and not exists(select 1 from public."TblP132ForeignTermExposure" x
                  where x."ForeignTermOccurrenceID"=o."ForeignTermOccurrenceID");

 create temporary table if not exists pg_temp.p132_tok(
   rn int,"OccurrenceID" bigint,"SurfaceText" text,"NormalizedTerm" text,
   "StartOffset" int,"EndOffset" int,"TermKind" text,cls text
 ) on commit drop;
 truncate pg_temp.p132_tok;

 -- Baseline stream: active single-token SQL17D rows. Existing multiword/manual/lexicon
 -- spans are protected and will outrank candidate chunks.
 insert into pg_temp.p132_tok
 select row_number() over(order by o."StartOffset")::int,o."ForeignTermOccurrenceID",
        o."SurfaceText",o."NormalizedTerm",o."StartOffset",o."EndOffset",o."TermKind",
        public."P132_EnglishTokenClass"(o."NormalizedTerm",o."TermKind")
 from public."TblP132ForeignTermOccurrence" o
 where o."ArticleID"=p_article_id and o."IsActive"
   and o."TermKind" in('term','function_word')
 order by o."StartOffset";

 create temporary table if not exists pg_temp.p132_chunk(
   "SurfaceText" text,"NormalizedTerm" text,"StartOffset" int,"EndOffset" int,
   priority int,confidence numeric,source_ids bigint[]
 ) on commit drop;
 truncate pg_temp.p132_chunk;

 -- High-confidence two-token grammatical chunks.
 insert into pg_temp.p132_chunk
 select substring(body from a1."StartOffset"+1 for a2."EndOffset"-a1."StartOffset"),
        lower(btrim(substring(body from a1."StartOffset"+1 for a2."EndOffset"-a1."StartOffset"))),
        a1."StartOffset",a2."EndOffset",260,0.9800,array[a1."OccurrenceID",a2."OccurrenceID"]
 from pg_temp.p132_tok a1 join pg_temp.p132_tok a2 on a2.rn=a1.rn+1
 where (a1.cls='quantifier' and a2.cls='than')
    or (a1.cls='time' and a2.cls='ago');

 -- Conservative 3-content-token candidate. It receives a modest confidence and is
 -- preferred over its overlapping 2-token candidates. This yields e.g.
 -- powered flying machine while still preserving source-token history.
 insert into pg_temp.p132_chunk
 select substring(body from a1."StartOffset"+1 for a3."EndOffset"-a1."StartOffset"),
        lower(btrim(substring(body from a1."StartOffset"+1 for a3."EndOffset"-a1."StartOffset"))),
        a1."StartOffset",a3."EndOffset",220,0.8000,
        array[a1."OccurrenceID",a2."OccurrenceID",a3."OccurrenceID"]
 from pg_temp.p132_tok a1
 join pg_temp.p132_tok a2 on a2.rn=a1.rn+1
 join pg_temp.p132_tok a3 on a3.rn=a1.rn+2
 where a1.cls='content' and a2.cls='content' and a3.cls='content'
   -- adjacency may contain spaces/punctuation but not sentence punctuation.
   and substring(body from a1."EndOffset"+1 for a2."StartOffset"-a1."EndOffset") !~ '[.!?;:]'
   and substring(body from a2."EndOffset"+1 for a3."StartOffset"-a2."EndOffset") !~ '[.!?;:]';

 -- Two-content-token fallback.
 insert into pg_temp.p132_chunk
 select substring(body from a1."StartOffset"+1 for a2."EndOffset"-a1."StartOffset"),
        lower(btrim(substring(body from a1."StartOffset"+1 for a2."EndOffset"-a1."StartOffset"))),
        a1."StartOffset",a2."EndOffset",200,0.8500,array[a1."OccurrenceID",a2."OccurrenceID"]
 from pg_temp.p132_tok a1 join pg_temp.p132_tok a2 on a2.rn=a1.rn+1
 where a1.cls='content' and a2.cls='content'
   and substring(body from a1."EndOffset"+1 for a2."StartOffset"-a1."EndOffset") !~ '[.!?;:]';

 -- Keep a non-overlapping winner set:
 -- known/manual/lexicon multiwords already present in the article always block a new chunk;
 -- among candidates, higher priority then longer span wins.
 create temporary table if not exists pg_temp.p132_chunk_winner(
   "SurfaceText" text,"NormalizedTerm" text,"StartOffset" int,"EndOffset" int,
   priority int,confidence numeric,source_ids bigint[]
 ) on commit drop;
 truncate pg_temp.p132_chunk_winner;

 for r in
   select c.* from pg_temp.p132_chunk c
   where not exists(
     select 1 from public."TblP132ForeignTermOccurrence" x
     where x."ArticleID"=p_article_id and x."IsActive"
       and x."TermKind" in('multiword','proper_noun','fixed_expression')
       and x."StartOffset"<c."EndOffset" and x."EndOffset">c."StartOffset"
   )
   order by c.priority desc,(c."EndOffset"-c."StartOffset") desc,c."StartOffset"
 loop
   if not exists(select 1 from pg_temp.p132_chunk_winner w
     where w."StartOffset"<r."EndOffset" and w."EndOffset">r."StartOffset") then
     insert into pg_temp.p132_chunk_winner values
       (r."SurfaceText",r."NormalizedTerm",r."StartOffset",r."EndOffset",
        r.priority,r.confidence,r.source_ids);
   end if;
 end loop;

 -- Insert chunk occurrences.
 for r in select * from pg_temp.p132_chunk_winner order by "StartOffset"
 loop
   if not exists(select 1 from public."TblP132ForeignTermOccurrence" x
      where x."ArticleID"=p_article_id and x."StartOffset"=r."StartOffset"
        and x."EndOffset"=r."EndOffset") then
     insert into public."TblP132ForeignTermOccurrence"
      ("ArticleID","LanguageCode","SurfaceText","NormalizedTerm","StartOffset","EndOffset",
       "TermKind","AnnotationMethod","AnnotationVersion","Confidence")
     values(p_article_id,'en',r."SurfaceText",r."NormalizedTerm",r."StartOffset",r."EndOffset",
       'multiword','rule','P132-TERM-0.3',r.confidence);
     n:=n+1;
   end if;
 end loop;

 -- Do NOT delete/disable source single tokens. They remain annotation provenance.
 -- Reader selection must prefer active longest multiword spans. SQL17D.1 exposes
 -- a canonical view for that purpose.
 return jsonb_build_object('article_id',p_article_id,'language','en',
   'chunks_inserted',n,'annotation_version','P132-TERM-0.3',
   'policy','conservative_multiword_chunking_source_tokens_preserved');
end $$;

revoke all on function public."P132_ChunkEnglishArticle"(bigint) from public,anon,authenticated;
grant execute on function public."P132_ChunkEnglishArticle"(bigint) to service_role;

-- Canonical non-overlapping reading terms.
-- Longest span wins; then manual/lexicon outrank rule; then confidence.
create or replace view public."VwP132ForeignReadingTerm" as
select o.*
from public."TblP132ForeignTermOccurrence" o
where o."IsActive"
and not exists(
 select 1 from public."TblP132ForeignTermOccurrence" z
 where z."ArticleID"=o."ArticleID" and z."IsActive"
   and z."StartOffset"<o."EndOffset" and z."EndOffset">o."StartOffset"
   and (
     (z."EndOffset"-z."StartOffset")>(o."EndOffset"-o."StartOffset")
     or (
       (z."EndOffset"-z."StartOffset")=(o."EndOffset"-o."StartOffset")
       and case z."AnnotationMethod" when 'manual' then 4 when 'lexicon' then 3
            when 'nlp' then 2 when 'ai' then 2 else 1 end
         > case o."AnnotationMethod" when 'manual' then 4 when 'lexicon' then 3
            when 'nlp' then 2 when 'ai' then 2 else 1 end
     )
   )
);
revoke all on public."VwP132ForeignReadingTerm" from public,anon,authenticated;
grant select on public."VwP132ForeignReadingTerm" to service_role;

-- Unified pipeline now performs chunking after segmentation for English.
create or replace function public."P132_AnnotateForeignArticle"(p_article_id bigint)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare lang text; base jsonb; seg jsonb; chunk jsonb;
begin
 select "LanguageCode" into lang from public."TblP132Article"
 where "ArticleID"=p_article_id and "IsPublished";
 if not found then raise exception 'Article not found'; end if;
 if lang not in('en','ja') then
   return jsonb_build_object('article_id',p_article_id,'reason','not_foreign_source');
 end if;
 base:=public."P132_AnnotateForeignTerms"(p_article_id);
 if lang='en' then
   seg:=public."P132_SegmentEnglishArticle"(p_article_id);
   chunk:=public."P132_ChunkEnglishArticle"(p_article_id);
   return jsonb_build_object('pipeline_version','P132-FOREIGN-ANNOT-0.3',
     'article_id',p_article_id,'language',lang,'lexicon_pass',base,
     'segmentation_pass',seg,'chunking_pass',chunk);
 end if;
 return jsonb_build_object('pipeline_version','P132-FOREIGN-ANNOT-0.3',
   'article_id',p_article_id,'language',lang,'lexicon_pass',base,
   'segmentation_pass',jsonb_build_object('status','deferred',
     'reason','Japanese requires language-specific segmentation'),
   'chunking_pass',jsonb_build_object('status','deferred'));
end $$;
revoke all on function public."P132_AnnotateForeignArticle"(bigint) from public,anon,authenticated;
grant execute on function public."P132_AnnotateForeignArticle"(bigint) to service_role;

select 'SQL17D.1 installed' as "Status",
       'P132-FOREIGN-ANNOT-0.3' as "PipelineVersion",
       'Conservative English multiword chunking; source tokens preserved' as "Scope";
