-- P132 SQL17E
-- Foreign Linguistic Analysis Architecture
-- External language-specific analyzers produce linguistic observations.
-- PostgreSQL stores versioned analysis and materializes selected learning terms.
--
-- Architecture:
-- Foreign Article -> Analysis Run -> Token/POS/Lemma/NER -> Term Candidates
-- -> conservative acceptance -> ForeignTermOccurrence -> Lexicon mapping -> learner evidence
--
-- IMPORTANT:
-- * Analyzer output is annotation, not learner evidence.
-- * Re-analysis may supersede annotation; Exposure/Evidence history is preserved.
-- * English and Japanese may use different analyzers/models under one contract.
-- * No external NLP service is called from PostgreSQL.

create table if not exists public."TblP132ForeignAnalysisRun"(
 "AnalysisRunID" bigint generated by default as identity primary key,
 "ArticleID" bigint not null references public."TblP132Article"("ArticleID") on delete cascade,
 "LanguageCode" text not null check("LanguageCode" in('en','ja')),
 "AnalyzerName" text not null,
 "AnalyzerVersion" text not null,
 "ModelName" text,
 "ModelVersion" text,
 "PipelineVersion" text not null default 'P132-LING-0.1',
 "ContentHash" text,
 "Status" text not null default 'pending'
   check("Status" in('pending','running','completed','failed','superseded')),
 "StartedAt" timestamptz,
 "CompletedAt" timestamptz,
 "ErrorMessage" text,
 "Metadata" jsonb not null default '{}'::jsonb,
 "CreatedAt" timestamptz not null default now()
);
create index if not exists "IdxP132ForeignAnalysisRunArticle"
 on public."TblP132ForeignAnalysisRun"("ArticleID","CreatedAt" desc);

create table if not exists public."TblP132ForeignLinguisticToken"(
 "LinguisticTokenID" bigint generated by default as identity primary key,
 "AnalysisRunID" bigint not null references public."TblP132ForeignAnalysisRun"("AnalysisRunID") on delete cascade,
 "TokenIndex" integer not null check("TokenIndex">=0),
 "SentenceIndex" integer,
 "SurfaceText" text not null,
 "Lemma" text,
 "UniversalPOS" text,
 "LanguagePOS" text,
 "Morphology" jsonb not null default '{}'::jsonb,
 "StartOffset" integer not null check("StartOffset">=0),
 "EndOffset" integer not null check("EndOffset">"StartOffset"),
 "EntityType" text,
 "IsStopword" boolean,
 "Confidence" numeric(5,4) check("Confidence" is null or "Confidence" between 0 and 1),
 unique("AnalysisRunID","TokenIndex"),
 unique("AnalysisRunID","StartOffset","EndOffset")
);
create index if not exists "IdxP132ForeignLinguisticTokenRunOffset"
 on public."TblP132ForeignLinguisticToken"("AnalysisRunID","StartOffset");

create table if not exists public."TblP132ForeignTermCandidate"(
 "ForeignTermCandidateID" bigint generated by default as identity primary key,
 "AnalysisRunID" bigint not null references public."TblP132ForeignAnalysisRun"("AnalysisRunID") on delete cascade,
 "SurfaceText" text not null,
 "NormalizedTerm" text not null,
 "Lemma" text,
 "StartOffset" integer not null check("StartOffset">=0),
 "EndOffset" integer not null check("EndOffset">"StartOffset"),
 "TermKind" text not null check("TermKind" in
   ('term','multiword','proper_noun','fixed_expression','function_word')),
 "CandidateMethod" text not null check("CandidateMethod" in
   ('token','noun_chunk','named_entity','mwe','morphology','dictionary','analyzer','manual')),
 "POSPattern" text,
 "Confidence" numeric(5,4) check("Confidence" is null or "Confidence" between 0 and 1),
 "SelectionStatus" text not null default 'candidate'
   check("SelectionStatus" in('candidate','accepted','rejected','superseded')),
 "SelectionReason" text,
 "CreatedAt" timestamptz not null default now(),
 unique("AnalysisRunID","StartOffset","EndOffset","CandidateMethod")
);
create index if not exists "IdxP132ForeignTermCandidateRun"
 on public."TblP132ForeignTermCandidate"("AnalysisRunID","StartOffset");

-- Provenance bridge: one materialized reading occurrence can be traced to the
-- linguistic analysis/candidate that created it. This avoids changing the 17A
-- occurrence table in a way that would disturb existing learner evidence.
create table if not exists public."TblP132ForeignOccurrenceProvenance"(
 "ForeignTermOccurrenceID" bigint primary key
   references public."TblP132ForeignTermOccurrence"("ForeignTermOccurrenceID") on delete cascade,
 "AnalysisRunID" bigint not null
   references public."TblP132ForeignAnalysisRun"("AnalysisRunID") on delete restrict,
 "ForeignTermCandidateID" bigint
   references public."TblP132ForeignTermCandidate"("ForeignTermCandidateID") on delete set null,
 "MaterializerVersion" text not null default 'P132-LING-MAT-0.1',
 "CreatedAt" timestamptz not null default now()
);
create index if not exists "IdxP132ForeignOccurrenceProvenanceRun"
 on public."TblP132ForeignOccurrenceProvenance"("AnalysisRunID");

alter table public."TblP132ForeignAnalysisRun" enable row level security;
alter table public."TblP132ForeignLinguisticToken" enable row level security;
alter table public."TblP132ForeignTermCandidate" enable row level security;
alter table public."TblP132ForeignOccurrenceProvenance" enable row level security;

revoke all on table
 public."TblP132ForeignAnalysisRun",
 public."TblP132ForeignLinguisticToken",
 public."TblP132ForeignTermCandidate",
 public."TblP132ForeignOccurrenceProvenance"
 from public,anon,authenticated;

grant select,insert,update,delete on table
 public."TblP132ForeignAnalysisRun",
 public."TblP132ForeignLinguisticToken",
 public."TblP132ForeignTermCandidate",
 public."TblP132ForeignOccurrenceProvenance"
 to service_role;

grant usage,select on sequence
 public."TblP132ForeignAnalysisRun_AnalysisRunID_seq",
 public."TblP132ForeignLinguisticToken_LinguisticTokenID_seq",
 public."TblP132ForeignTermCandidate_ForeignTermCandidateID_seq"
 to service_role;

-- Back-office API: create a run before an Edge Function / NLP worker uploads results.
create or replace function public."P132_BeginForeignAnalysis"(
 p_article_id bigint,p_analyzer_name text,p_analyzer_version text,
 p_model_name text default null,p_model_version text default null,p_metadata jsonb default '{}'::jsonb)
returns bigint language plpgsql security definer set search_path=public,pg_temp as $$
declare a public."TblP132Article"; rid bigint;
begin
 select * into a from public."TblP132Article"
 where "ArticleID"=p_article_id and "IsPublished" and "LanguageCode" in('en','ja');
 if not found then raise exception 'Foreign article not found'; end if;
 if nullif(btrim(p_analyzer_name),'') is null or nullif(btrim(p_analyzer_version),'') is null
   then raise exception 'Analyzer name/version required'; end if;
 insert into public."TblP132ForeignAnalysisRun"
 ("ArticleID","LanguageCode","AnalyzerName","AnalyzerVersion","ModelName","ModelVersion",
  "PipelineVersion","ContentHash","Status","StartedAt","Metadata")
 values(p_article_id,a."LanguageCode",p_analyzer_name,p_analyzer_version,p_model_name,p_model_version,
  'P132-LING-0.1',a."ContentHash",'running',now(),coalesce(p_metadata,'{}'::jsonb))
 returning "AnalysisRunID" into rid;
 return rid;
end $$;
revoke all on function public."P132_BeginForeignAnalysis"(bigint,text,text,text,text,jsonb)
 from public,anon,authenticated;
grant execute on function public."P132_BeginForeignAnalysis"(bigint,text,text,text,text,jsonb)
 to service_role;

-- Upload analyzer tokens as JSONB array.
-- Required per token: token_index, surface_text, start_offset, end_offset.
-- Optional: sentence_index, lemma, universal_pos, language_pos, morphology,
-- entity_type, is_stopword, confidence.
create or replace function public."P132_SaveForeignLinguisticTokens"(
 p_analysis_run_id bigint,p_tokens jsonb)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare x jsonb;n int:=0;
begin
 if not exists(select 1 from public."TblP132ForeignAnalysisRun"
   where "AnalysisRunID"=p_analysis_run_id and "Status" in('running','pending'))
   then raise exception 'Analysis run not writable'; end if;
 if jsonb_typeof(p_tokens)<>'array' then raise exception 'Tokens must be a JSON array'; end if;
 delete from public."TblP132ForeignLinguisticToken" where "AnalysisRunID"=p_analysis_run_id;
 for x in select value from jsonb_array_elements(p_tokens)
 loop
   insert into public."TblP132ForeignLinguisticToken"
   ("AnalysisRunID","TokenIndex","SentenceIndex","SurfaceText","Lemma","UniversalPOS","LanguagePOS",
    "Morphology","StartOffset","EndOffset","EntityType","IsStopword","Confidence")
   values(p_analysis_run_id,(x->>'token_index')::int,nullif(x->>'sentence_index','')::int,
    x->>'surface_text',nullif(x->>'lemma',''),nullif(x->>'universal_pos',''),
    nullif(x->>'language_pos',''),coalesce(x->'morphology','{}'::jsonb),
    (x->>'start_offset')::int,(x->>'end_offset')::int,nullif(x->>'entity_type',''),
    nullif(x->>'is_stopword','')::boolean,nullif(x->>'confidence','')::numeric);
   n:=n+1;
 end loop;
 return jsonb_build_object('analysis_run_id',p_analysis_run_id,'tokens_saved',n);
end $$;
revoke all on function public."P132_SaveForeignLinguisticTokens"(bigint,jsonb)
 from public,anon,authenticated;
grant execute on function public."P132_SaveForeignLinguisticTokens"(bigint,jsonb) to service_role;

-- Upload term candidates separately from tokens. This is where an English NLP
-- analyzer can provide noun chunks/MWEs/NER and a Japanese analyzer can provide
-- morphological terms/compound nouns. Database does not force the two languages
-- to share a segmentation algorithm.
create or replace function public."P132_SaveForeignTermCandidates"(
 p_analysis_run_id bigint,p_candidates jsonb)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare x jsonb;n int:=0; lang text;
begin
 select "LanguageCode" into lang from public."TblP132ForeignAnalysisRun"
 where "AnalysisRunID"=p_analysis_run_id and "Status" in('running','pending');
 if not found then raise exception 'Analysis run not writable'; end if;
 if jsonb_typeof(p_candidates)<>'array' then raise exception 'Candidates must be a JSON array'; end if;
 delete from public."TblP132ForeignTermCandidate" where "AnalysisRunID"=p_analysis_run_id;
 for x in select value from jsonb_array_elements(p_candidates)
 loop
   insert into public."TblP132ForeignTermCandidate"
   ("AnalysisRunID","SurfaceText","NormalizedTerm","Lemma","StartOffset","EndOffset",
    "TermKind","CandidateMethod","POSPattern","Confidence","SelectionStatus")
   values(p_analysis_run_id,x->>'surface_text',
    coalesce(nullif(x->>'normalized_term',''),
      case when lang='en' then lower(btrim(x->>'surface_text')) else btrim(x->>'surface_text') end),
    nullif(x->>'lemma',''),(x->>'start_offset')::int,(x->>'end_offset')::int,
    coalesce(nullif(x->>'term_kind',''),'term'),
    coalesce(nullif(x->>'candidate_method',''),'analyzer'),nullif(x->>'pos_pattern',''),
    nullif(x->>'confidence','')::numeric,'candidate');
   n:=n+1;
 end loop;
 return jsonb_build_object('analysis_run_id',p_analysis_run_id,'candidates_saved',n);
end $$;
revoke all on function public."P132_SaveForeignTermCandidates"(bigint,jsonb)
 from public,anon,authenticated;
grant execute on function public."P132_SaveForeignTermCandidates"(bigint,jsonb) to service_role;

-- Materialize a non-overlapping candidate set into the existing 17A occurrence model.
-- Selection is deliberately conservative:
-- named_entity/fixed_expression/mwe/noun_chunk outrank generic token candidates;
-- higher confidence and longer spans break ties.
-- Existing manual/lexicon occurrences outrank NLP materialization.
create or replace function public."P132_MaterializeForeignAnalysis"(p_analysis_run_id bigint)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare r record;runrow public."TblP132ForeignAnalysisRun";oid bigint;n int:=0;mapped int:=0;
begin
 select * into runrow from public."TblP132ForeignAnalysisRun"
 where "AnalysisRunID"=p_analysis_run_id and "Status" in('running','completed');
 if not found then raise exception 'Analysis run not materializable'; end if;

 create temporary table if not exists pg_temp.p132_ling_winner(
   "ForeignTermCandidateID" bigint,"SurfaceText" text,"NormalizedTerm" text,
   "StartOffset" int,"EndOffset" int,"TermKind" text,"Confidence" numeric
 ) on commit drop;
 truncate pg_temp.p132_ling_winner;

 for r in
   select c.*,
     case c."CandidateMethod"
       when 'named_entity' then 600 when 'mwe' then 550 when 'dictionary' then 525
       when 'noun_chunk' then 500 when 'morphology' then 450
       when 'manual' then 650 when 'analyzer' then 350 else 200 end as pri
   from public."TblP132ForeignTermCandidate" c
   where c."AnalysisRunID"=p_analysis_run_id and c."SelectionStatus"='candidate'
   order by pri desc,coalesce(c."Confidence",0) desc,
            (c."EndOffset"-c."StartOffset") desc,c."StartOffset"
 loop
   if not exists(select 1 from pg_temp.p132_ling_winner w
      where w."StartOffset"<r."EndOffset" and w."EndOffset">r."StartOffset")
      and not exists(
       select 1 from public."TblP132ForeignTermOccurrence" o
       where o."ArticleID"=runrow."ArticleID" and o."IsActive"
         and o."AnnotationMethod" in('manual','lexicon')
         and o."StartOffset"<r."EndOffset" and o."EndOffset">r."StartOffset")
   then
     insert into pg_temp.p132_ling_winner values
      (r."ForeignTermCandidateID",r."SurfaceText",r."NormalizedTerm",
       r."StartOffset",r."EndOffset",r."TermKind",r."Confidence");
   end if;
 end loop;

 -- Supersede only unexposed prior NLP materializations for this article.
 update public."TblP132ForeignTermOccurrence" o set "IsActive"=false
 where o."ArticleID"=runrow."ArticleID" and o."AnnotationMethod"='nlp' and o."IsActive"
   and not exists(select 1 from public."TblP132ForeignTermExposure" e
                  where e."ForeignTermOccurrenceID"=o."ForeignTermOccurrenceID");

 for r in select * from pg_temp.p132_ling_winner order by "StartOffset"
 loop
   -- Unique article/offset constraint means an old rule row at the same exact span
   -- must be reused rather than duplicated. If exposed, preserve its identity/history.
   select "ForeignTermOccurrenceID" into oid
   from public."TblP132ForeignTermOccurrence"
   where "ArticleID"=runrow."ArticleID"
     and "StartOffset"=r."StartOffset" and "EndOffset"=r."EndOffset"
   limit 1;

   if oid is null then
     insert into public."TblP132ForeignTermOccurrence"
     ("ArticleID","LanguageCode","SurfaceText","NormalizedTerm","StartOffset","EndOffset",
      "TermKind","AnnotationMethod","AnnotationVersion","Confidence")
     values(runrow."ArticleID",runrow."LanguageCode",r."SurfaceText",r."NormalizedTerm",
      r."StartOffset",r."EndOffset",r."TermKind",'nlp','P132-TERM-0.4',r."Confidence")
     returning "ForeignTermOccurrenceID" into oid;
   else
     -- Only upgrade annotation metadata when doing so does not rewrite learner history.
     if not exists(select 1 from public."TblP132ForeignTermExposure"
                   where "ForeignTermOccurrenceID"=oid) then
       update public."TblP132ForeignTermOccurrence" set
        "SurfaceText"=r."SurfaceText","NormalizedTerm"=r."NormalizedTerm",
        "TermKind"=r."TermKind","AnnotationMethod"='nlp',
        "AnnotationVersion"='P132-TERM-0.4',"Confidence"=r."Confidence","IsActive"=true
       where "ForeignTermOccurrenceID"=oid;
     end if;
   end if;

   insert into public."TblP132ForeignOccurrenceProvenance"
    ("ForeignTermOccurrenceID","AnalysisRunID","ForeignTermCandidateID","MaterializerVersion")
   values(oid,p_analysis_run_id,r."ForeignTermCandidateID",'P132-LING-MAT-0.1')
   on conflict("ForeignTermOccurrenceID") do update set
    "AnalysisRunID"=excluded."AnalysisRunID",
    "ForeignTermCandidateID"=excluded."ForeignTermCandidateID",
    "MaterializerVersion"=excluded."MaterializerVersion",
    "CreatedAt"=now();

   update public."TblP132ForeignTermCandidate" set
    "SelectionStatus"='accepted',"SelectionReason"='materialized'
   where "ForeignTermCandidateID"=r."ForeignTermCandidateID";

   perform public."P132_MapForeignOccurrenceToLexicon"(oid);
   if exists(select 1 from public."TblP132ForeignTermOccurrence"
             where "ForeignTermOccurrenceID"=oid and "ConceptID" is not null)
      then mapped:=mapped+1; end if;
   n:=n+1; oid:=null;
 end loop;

 update public."TblP132ForeignTermCandidate" c set
  "SelectionStatus"='rejected',
  "SelectionReason"=coalesce(c."SelectionReason",'overlap_or_lower_priority')
 where c."AnalysisRunID"=p_analysis_run_id and c."SelectionStatus"='candidate';

 update public."TblP132ForeignAnalysisRun" set
  "Status"='completed',"CompletedAt"=coalesce("CompletedAt",now())
 where "AnalysisRunID"=p_analysis_run_id;

 return jsonb_build_object('analysis_run_id',p_analysis_run_id,
   'article_id',runrow."ArticleID",'language',runrow."LanguageCode",
   'occurrences_materialized',n,'mapped_to_lexicon',mapped,
   'pipeline_version','P132-LING-0.1','annotation_version','P132-TERM-0.4');
end $$;
revoke all on function public."P132_MaterializeForeignAnalysis"(bigint)
 from public,anon,authenticated;
grant execute on function public."P132_MaterializeForeignAnalysis"(bigint) to service_role;

create or replace function public."P132_FailForeignAnalysis"(p_analysis_run_id bigint,p_error text)
returns void language plpgsql security definer set search_path=public,pg_temp as $$
begin
 update public."TblP132ForeignAnalysisRun"
 set "Status"='failed',"CompletedAt"=now(),"ErrorMessage"=left(coalesce(p_error,'Unknown error'),4000)
 where "AnalysisRunID"=p_analysis_run_id and "Status" in('pending','running');
end $$;
revoke all on function public."P132_FailForeignAnalysis"(bigint,text)
 from public,anon,authenticated;
grant execute on function public."P132_FailForeignAnalysis"(bigint,text) to service_role;

-- Reader-facing canonical view: linguistic/NLP annotation outranks heuristic rule
-- annotation when spans overlap; manual/lexicon remain authoritative. Then prefer
-- longer spans within the same authority tier.
create or replace view public."VwP132ForeignReadingTerm" as
select o.*
from public."TblP132ForeignTermOccurrence" o
where o."IsActive"
and not exists(
 select 1 from public."TblP132ForeignTermOccurrence" z
 where z."ArticleID"=o."ArticleID" and z."IsActive"
   and z."StartOffset"<o."EndOffset" and z."EndOffset">o."StartOffset"
   and (
     case z."AnnotationMethod" when 'manual' then 5 when 'lexicon' then 4
          when 'nlp' then 3 when 'ai' then 2 else 1 end
       > case o."AnnotationMethod" when 'manual' then 5 when 'lexicon' then 4
          when 'nlp' then 3 when 'ai' then 2 else 1 end
     or (
       case z."AnnotationMethod" when 'manual' then 5 when 'lexicon' then 4
            when 'nlp' then 3 when 'ai' then 2 else 1 end
       = case o."AnnotationMethod" when 'manual' then 5 when 'lexicon' then 4
            when 'nlp' then 3 when 'ai' then 2 else 1 end
       and (z."EndOffset"-z."StartOffset")>(o."EndOffset"-o."StartOffset")
     )
   )
);
revoke all on public."VwP132ForeignReadingTerm" from public,anon,authenticated;
grant select on public."VwP132ForeignReadingTerm" to service_role;

-- IMPORTANT reader fix: 17C originally read every active raw occurrence.
-- From SQL17E onward it must read the canonical non-overlapping view, otherwise
-- raw tokens and multiword/NLP spans would both receive red/green controls.
create or replace function public."P132_GetForeignArticleTerms"(p_article_id bigint,p_reading_session_id uuid)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare uid uuid:=auth.uid(); a public."TblP132Article"; r record; eid bigint; arr jsonb:='[]'::jsonb; meaning text;
begin
 if uid is null then raise exception 'Authentication required'; end if;
 select * into a from public."TblP132Article"
 where "ArticleID"=p_article_id and "IsPublished" and "LanguageCode" in('en','ja');
 if not found then raise exception 'Foreign article not found'; end if;
 if not exists(select 1 from public."TblP132ReadingSession" s
   where s."ReadingSessionID"=p_reading_session_id and s."UserID"=uid
     and s."ArticleID"=p_article_id and s."EndedAt" is null)
   then raise exception 'Invalid reading session'; end if;

 for r in
   select o.*,s."LatestEvidenceType"
   from public."VwP132ForeignReadingTerm" o
   left join public."TblP132LearnerForeignTermState" s on s."UserID"=uid
    and s."LanguageCode"=o."LanguageCode" and s."NormalizedTerm"=o."NormalizedTerm"
   where o."ArticleID"=p_article_id
   order by o."StartOffset"
 loop
   select "ForeignTermExposureID" into eid from public."TblP132ForeignTermExposure"
   where "ReadingSessionID"=p_reading_session_id
     and "ForeignTermOccurrenceID"=r."ForeignTermOccurrenceID";
   if eid is null then
     insert into public."TblP132ForeignTermExposure"
     ("UserID","ReadingSessionID","ArticleID","ForeignTermOccurrenceID","ConceptID","LanguageCode","NormalizedTerm",
      "AlgorithmVersion")
     values(uid,p_reading_session_id,p_article_id,r."ForeignTermOccurrenceID",r."ConceptID",
      r."LanguageCode",r."NormalizedTerm",'P132-FOREIGN-0.2')
     returning "ForeignTermExposureID" into eid;
   end if;
   select coalesce(pm."MeaningZh",c."MeaningZh",c."CanonicalZh") into meaning
   from (select 1) z
   left join public."TblP132PersonalTermMeaning" pm on pm."UserID"=uid
      and pm."LanguageCode"=r."LanguageCode" and pm."NormalizedTerm"=r."NormalizedTerm" and pm."IsActive"
   left join public."TblP132VocabularyConcept" c on c."ConceptID"=r."ConceptID";
   arr:=arr||jsonb_build_array(jsonb_build_object(
    'foreign_term_occurrence_id',r."ForeignTermOccurrenceID",'exposure_id',eid,
    'surface_text',r."SurfaceText",'normalized_term',r."NormalizedTerm",
    'start_offset',r."StartOffset",'end_offset',r."EndOffset",
    'term_kind',r."TermKind",'meaning_zh',meaning,
    'annotation_method',r."AnnotationMethod",'annotation_version',r."AnnotationVersion",
    'show_translation',true,
    'show_understand',coalesce(r."LatestEvidenceType",'')<>'understand'));
 end loop;
 return jsonb_build_object('article_id',p_article_id,'language',a."LanguageCode",
   'algorithm_version','P132-FOREIGN-0.2','terms',arr);
end $$;
revoke all on function public."P132_GetForeignArticleTerms"(bigint,uuid) from public,anon;
grant execute on function public."P132_GetForeignArticleTerms"(bigint,uuid) to authenticated;

select 'SQL17E installed' as "Status",
       'P132-LING-0.1' as "LinguisticPipelineVersion",
       'P132-TERM-0.4' as "MaterializedAnnotationVersion",
       'External analyzer contract + versioned token/POS/NER/candidate storage' as "Scope";
